### ISSUE TITLE
File unavailable when I try to DeleteDirectory

### ISSUE THREAD

**Issue by pbindy** [hgupta9/FluentFTP#99] opened 2017-05-13 13:53 UTC
I come back because I'm experiencing another issue than issue 67 with the DeleteDirectory method .
(https://github.com/hgupta9/FluentFTP/issues/67)

I upload some folders and files in the beginning of my process and around 10mn later, I delete a folder which contains files
I use
FtpClient.DeleteDirectory(folderPath, true, true);

but I sometimes get the error:

Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.

Thank you for your help...

**Comment by pbindy** [comment] 2017-05-15 08:46
I've updated to version 17.2.0 but I'm totally unable to delete a directory and I'm really puzzled with it.
I get the issue 

Initially, the directory contains files, but I remove them manually before executing the command DeleteDirectory, but even this way, it doesn't work.

For me, the command DeleteDirectory doesn't work and if I delete the directory with Filezilla, it works without any issue.

I get the following exception when executing DeleteDirectory(folderPath)
File unavailable (e.g., file busy).

Please let me know how it should be done.

The folder I'm trying to access is on Win CE and is called /FlashDisk/TestStand

Here is my current code.

```
public static bool Connect(string ftpIpAddress, string ftpUserId = "", string ftpPassword = "")
        {
            try
            {
                if (FtpClient == null || !FtpClient.IsConnected)
                {
                    string username = ftpUserId == string.Empty ? "anonymous" : ftpUserId;
                    string password = ftpPassword == string.Empty ? "anonymous" : ftpPassword;

                    FtpClient = new FluentFTP.FtpClient
                    {
                        Host = ftpIpAddress,
                        Credentials = new NetworkCredential(username, password),

                        //needs this encoding 1252 because of special characters in filenames (ä, ë, ö)
                        //https://en.wikipedia.org/wiki/Windows-1252#Character_set
                        Encoding = Encoding.GetEncoding(1252)
                    };

                    FtpClient.Connect();

                    return FtpClient.IsConnected;
                }
            }
            catch (Exception ex)
            {
                Display.AddTextToLog(string.Format(Resources.FtpFunctions_FtpCommunication_Error));
                LogsCall.CallLogs(LogType.Error, ex.Message);
                LogsCall.CallLogs(LogType.Error, string.Format("Issue while connecting to {0}", ftpIpAddress));
                Common.Message(MessageTypes.Error, Resources.FtpFunctions_FtpCommunication_Error,
                    "Ftp Communication Error", FormStartPosition.CenterScreen);

                return false;
            }

            return true;
        }


public static bool FtpDeleteFolder(string folderPath, string ftpIpAddress, string ftpUserId = "",
            string ftpPassword = "")
        {
            try
            {
                if (Connect(ftpIpAddress, ftpUserId, ftpPassword))
                {
                    //Quick fix as the command DeleteDirectory has some issues
                    //to replace once there is a better solution to directly delete a folder and its children
                    if (folderPath.Contains(Constants.TestStand))
                    {
                        var filesToDelete = FtpClient.GetListing(folderPath);

                        foreach (var currentFile in filesToDelete)
                        {
                            FtpClient.DeleteFile(currentFile.FullName);
                            Display.AddTextToLog(
                                string.Format("File {0} was successfully deleted", currentFile.FullName));
                            LogsCall.CallLogs(LogType.Info,
                                string.Format("File {0} was successfully deleted", currentFile.FullName));
                        }
                    }
     
                    if (FtpClient.DirectoryExists(folderPath))
                    {                      
                    //Issue with the following line, internal problem of FluentFTP 
                            FtpClient.DeleteDirectory(folderPath);
                            Display.AddTextToLog(string.Format("Folder {0} was successfully deleted", folderPath));
                            LogsCall.CallLogs(LogType.Info,
                                string.Format("Folder {0} was successfully deleted", folderPath));

                            return true;                        
                    }
                }
            }
            catch (Exception ex)
            {
                Display.AddTextToLog(string.Format("Folder {0} could not be deleted", folderPath));
                LogsCall.CallLogs(LogType.Error, string.Format("Folder {0} could not be deleted", folderPath));
                LogsCall.CallLogs(LogType.Error, ex.Message);
            }
            return false;
        }
```


I also tried to change the folder permissions before deleting the folder but the following lines return a FtpCommandException (Syntax error, command unrecognized.)

```
 if (!(reply = FtpClient.Execute(string.Format("CHMOD -r 777 {0}/", folderPath))).Success)
                        {
                            throw new FtpCommandException(reply);
                        }

```

I also thought that the folder I'm trying to delete is the current working directory but it is not the case.

Please help me on this. I really like FluentFTP but I have to admit that if DeleteDirectory method isn't working it's a big turn-off!

**Comment by hgupta9** [comment] 2017-05-15 16:05
I just tested DeleteDirectory() and it works fine on my end. If you want you can pass the raw delete dir command and see what your FTP server replies with. Also, you can change the permissions using the proper Chmod() API but I don't think its supported by Windows based FTP servers.

> Execute("RMD \path\to\dir\")

Why don't you see the FileZilla log and simply send exactly those commands to your server. If its doing something different, you can copy its behavior.

**Comment by jblacker** [comment] 2017-05-18 14:39
@pbindy Just a heads up the message:

>Unable to read data from the transport connection : An existing connection was forcibly closed by the remote host

Means that on the server the [FTP daemon] service isn't running (probably not the case) or the service is currently still busy performing another operation.  Do you know the type of FTP Server that's installed on the remote machine?  It almost sounds like the server is returning a message indicating it has completed an operation that's actually still currently processing, so when FluentFTP attempts to issue the next command the service says "um...I'm not done.  Go away!" which is the error message that you're seeing.  Did your own `FtpDeleteFolder` method work successfully?  Lastly, were you able to get the FileZilla commands sent?

**Comment by pbindy** [comment] 2017-05-18 14:57
For the FTP server, well it's the one coming by default with Windows CE. Where could I check which type of FTP server is it?

My method `FtpDeleteFolder` doesn't work 100%, sometimes the folder I want to delete is not deleted, but it's not always the case and I don't know the difference between when it is successful and not.

Even when I try to empty the folder before using `DeleteFolder` it is not 100% successful.

I'm wondering why sometimes the folder is not deleted, I can't reproduce this bug systematically 

The Filezilla command is the following: ` SITE CHMOD 777` folderName

**Comment by jblacker** [comment] 2017-05-18 16:18
@pbindy According to [this from MSDN](https://msdn.microsoft.com/en-us/library/ms881872.aspx) the WindowsCE implementation of FTP is the bare minimum, and open to customization via source code. 
 Windows based FTP servers don't typically accept `CHMOD` since UNIX permissions are different from Windows permissions...and `CHMOD` is a UNIX command.  Are you sure FileZilla is issuing that command successfully?  I don't have any Windows CE machines to test against, but I haven't been able to reproduce this on FTP servers on either Windows or Linux (Debian).  It might be an issue with the FTP server implementation rather than the FluentFTP library, but it's too early to tell just yet.  What happened when you issued the command that @hgupta9  asked in his post?  He wanted you to issue the raw FTP command:
```
client.Execute("RMD \path\to\dir");
```
Try this both with files in the folder and with the files in the folder deleted.

The raw command for deleting a file is:
```
client.Execute("DELE \path\to\file\filename.ext");
```

**Comment by pbindy** [comment] 2017-05-19 07:28
@jblacker Thank you for your post. 
I've made some testing and the command CHMOD indeed doesn't work in Filezilla
`09:22:29	Response:	500 Syntax error, command unrecognized.`

Regarding the commands here are my results:

Command: 
`RMD /FlashDisk/{FolderName}`

When the folder is not empty, the FtpReply returns an error code 550 - File unavailable

When the folder is empty, the FtpReply is successful and returns the code 250 - Requested file action okay, completed


I tried to delete files as well with the command
`DELE /FlashDisk/TestStand/{fileName}png`

and the FtpReply is successful and returns the code 250 - Requested file action okay, completed

Hope it helps...

**Comment by hgupta9** [comment] 2017-05-19 08:19
My point was whichever commands work in FileZilla for deleting a folder, look at the FTP log and run the same commands with FluentFTP! It can't fail!

**Comment by pbindy** [comment] 2017-05-19 09:05
@hgupta9 Ok I get your point now.

From Filezilla log file, here is what it does:

```
Status: Deleting 3 files from "/FlashDisk/TestStand"
Command: CWD /FlashDisk/TestStand
Response: 250 Requested file action okay, completed.
**Command: DELE EthNamedPipeConnector.exe**
Response: 250 Requested file action okay, completed.
**Command: DELE EthComLib.dll**
Response: 250 Requested file action okay, completed.
**Command: DELE EthComConnector.exe**
Response: 250 Requested file action okay, completed.
**Command: CWD /FlashDisk**
Response: 250 Requested file action okay, completed.
**Command: RMD TestStand**
```

I could implement that with the method Execute but I just hoped it could work with simply calling the method **DeleteDirectory**

**Comment by hgupta9** [comment] 2017-05-19 10:07
Of course it should. Can you enable trace logging using this [FAQ](https://github.com/hgupta9/FluentFTP#faq_trace) and copy the trace when you call DeleteDirectory? I need to know if its a problem with the GetListing (that discovers the files in the folder) or if its a problem with deleting the directory (RMD command)

**Comment by pbindy** [comment] 2017-05-19 10:47
@hgupta9 
Ok I'm going to do that and let you know

**Comment by pbindy** [comment] 2017-05-19 11:15
[fluentFtpLogFile.txt](https://github.com/hgupta9/FluentFTP/files/1013958/fluentFtpLogFile.txt)

Here is the log file. as you can see, I'm unable to delete the directory TestStand

**Comment by jblacker** [comment] 2017-05-19 14:25
@pbindy Do you mind posing the FluentFTP commands (in order) that you issued that generated the log file?  I can assume most of it, but just want to make sure my assumptions match what actually was coded.  You don't need to post your all of your code, just the method calls made on `FtpClient`

**Comment by hgupta9** [comment] 2017-05-19 15:20
@jblacker I think the whole code dump is here : https://github.com/hgupta9/FluentFTP/issues/99#issuecomment-301414116

**Comment by hgupta9** [comment] 2017-05-19 15:25
@jblacker Maybe we should log each function call and the args that were passed. All are strings/ints so should be easy to read in the log itself. Something like:

```
# Connect("...", "...")
TYPE I
200 Command okay.

# UploadFile("...", "...", FtpExists.Overwrite)
SIZE FlashDisk/TestStand/EthNamedPipeConnector.exe
500 Syntax error, command unrecognized.
EPSV
229 Entering extended passive mode (|||49461|).
STOR FlashDisk/TestStand/EthNamedPipeConnector.exe
125 Data connection already open; transfer starting.
226 Closing data connection. 

# DeleteDirectory("....", true, false, FtpVerify.None)
PWD
257 "/".
TYPE I
200 Command okay.
EPSV
229 Entering extended passive mode (|||49465|).
LIST /FlashDisk/TestStand
125 Data connection already open; transfer starting.
05-19-17  13:03                32768 EthComConnector.exe
05-19-17  13:03                23040 EthComLib.dll
05-19-17  13:03               461312 EthNamedPipeConnector.exe
226 Closing data connection. 
Disposing FtpSocketStream...
Confirmed format Windows
DELE /FlashDisk/TestStand/EthComConnector.exe
250 Requested file action okay, completed.
Disposing FtpSocketStream...
DELE /FlashDisk/TestStand/EthComLib.dll
250 Requested file action okay, completed.
DELE /FlashDisk/TestStand/EthNamedPipeConnector.exe
250 Requested file action okay, completed.
```

**Comment by hgupta9** [comment] 2017-05-19 15:29
@pbindy Are you still calling GetListing() yourself? Just try creating your files/folders, then try deleting it using DeleteDirectory(). If you keep using custom code its harder to debug since we can't fix anything on our end. And can you post the latest code you are using?

**Comment by hgupta9** [comment] 2017-05-19 15:38
@pbindy As of now I can think of 2 possible issues:

1. A previous command is hanging up the server, so when you call DeleteDirectory() it cannot delete it because its busy.

2. The way we are deleting is not acceptable to Windows CE (ie. we do `RMD /full/path/of/dir` while the logs of FileZilla do `CWD /full/path/of/` then `RMD dir`)

3. Also for some reason I see no `RMD` (delete dir) commands in the log. This means that the error "File unavailable (e.g., file busy)." is coming from the LIST command, as in, the server cannot list the contents of the dir because its busy.

**Comment by hgupta9** [comment] 2017-05-19 15:42
@pbindy Please dump the entire code you are using (relating to FluentFTP). I'll change it and send it back for you to try. Its easiest for both of us like that.

**Comment by pbindy** [comment] 2017-05-19 19:00
Here is my code in order:

1. Connect
if (FtpClient == null)
                {
                    string username = ftpUserId == string.Empty ? "anonymous" : ftpUserId;
                    string password = ftpPassword == string.Empty ? "anonymous" : ftpPassword;

                    FtpClient = new FluentFTP.FtpClient
                    {
                        Host = ftpIpAddress,
                        Credentials = new NetworkCredential(username, password),

                        //needs this encoding 1252 because of special characters in filenames (ä, ë, ö)
                        //https://en.wikipedia.org/wiki/Windows-1252#Character_set
                        Encoding = Encoding.GetEncoding(1252)
                    };

                    //create log file for FluentFTP
                    FtpTrace.FlushOnWrite = true;
                    FtpTrace.AddListener(new TextWriterTraceListener("C:/TestStand/Logs/fluentFtpLogFile.txt")
                    {
                        Filter = new EventTypeFilter(SourceLevels.Error)
                    });

                }

                if (!FtpClient.IsConnected)
                {
                    FtpClient.Connect();
                }`
2. Before using DeleteDirectory, I manually delete all the children files.
`FtpClient.GetListing(source);`

3. Delete of the children files
`      FtpClient.DeleteFile(filePath.Trim());`

4. Check if directory exists and delete it
```

  if (FtpClient.DirectoryExists(folderPath))
                    {
                        var listing = FtpClient.GetListing(folderPath);

                        if (listing.Length > 0)
                        {
                            Display.AddTextToLog(string.Format("The folder {0} is not yet empty", folderPath));
                            LogsCall.CallLogs(LogType.Warn, string.Format("The folder {0} is not yet empty", folderPath));
                        }

                        //folder TestStand is empty, delete it
                        FtpClient.DeleteDirectory(folderPath);
```

**Comment by hgupta9** [comment] 2017-05-20 06:46
@pbindy Thanks. Use this code please.

**Option A**
```
if (FtpClient == null)
{
	string username = ftpUserId == string.Empty ? "anonymous" : ftpUserId;
	string password = ftpPassword == string.Empty ? "anonymous" : ftpPassword;

	FtpClient = new FluentFTP.FtpClient
	{
		Host = ftpIpAddress,
		Credentials = new NetworkCredential(username, password),

		//needs this encoding 1252 because of special characters in filenames (ä, ë, ö)
		//https://en.wikipedia.org/wiki/Windows-1252#Character_set
		Encoding = Encoding.GetEncoding(1252)
	};

	//create log file for FluentFTP
	FtpTrace.FlushOnWrite = true;
	FtpTrace.AddListener(new TextWriterTraceListener("C:/TestStand/Logs/fluentFtpLogFile.txt")
	{
		Filter = new EventTypeFilter(SourceLevels.Error)
	});

}

if (!FtpClient.IsConnected){
	FtpClient.Connect();
}

if (FtpClient.DirectoryExists(folderPath)){
	FtpClient.DeleteDirectory(folderPath);
}
```

If that doesn't work then use this:

**Option B:**
```

string username = ftpUserId == string.Empty ? "anonymous" : ftpUserId;
string password = ftpPassword == string.Empty ? "anonymous" : ftpPassword;

FtpClient = new FluentFTP.FtpClient
{
	Host = ftpIpAddress,
	Credentials = new NetworkCredential(username, password),

	//needs this encoding 1252 because of special characters in filenames (ä, ë, ö)
	//https://en.wikipedia.org/wiki/Windows-1252#Character_set
	Encoding = Encoding.GetEncoding(1252)
};

//create log file for FluentFTP
FtpTrace.FlushOnWrite = true;
FtpTrace.AddListener(new TextWriterTraceListener("C:/TestStand/Logs/fluentFtpLogFile.txt")
{
	Filter = new EventTypeFilter(SourceLevels.Error)
});

FtpClient.Connect();

if (FtpClient.DirectoryExists(folderPath)){
	FtpClient.DeleteDirectory(folderPath);
}

FtpClient.Disconnect();
```

**Comment by hgupta9** [comment] 2017-05-20 06:48
@jblacker Isn't it weird that even though he is only logging errors (SourceLevels.Error) to a file still we have all the debugging info (info, warn, etc) saved to a file? Is that a bug?

**Comment by pbindy** [comment] 2017-05-22 06:26
@hgupta9 

Ok I'll try, but can you tell me in more details how this code would resolve the issue I'm having ?

Because we are only focusing on the ftpClient object and its connection

**Comment by hgupta9** [comment] 2017-05-22 07:18
Solution A is not what you have. I have removed the way you do GetListing and manually delete files. Let DeleteDirectory delete all the inner files. If it has bugs then I'll check.

Solution B reconnects everytime, by creating a new FTP client and disconnecting at the end.

Just try it and let me know....

**Comment by pbindy** [comment] 2017-05-22 08:12
Ok I understand better now. In the beginning, I had DeleteDirectory without manually deleting the files. I added the part to delete the files manually because DeleteDirectory was failing, that's the reason.

Anyway, I'll try and test and let you know.

**Comment by pbindy** [comment] 2017-05-22 10:54
@hgupta9 
I've made some testing for Solution A and B and none of them are working.

here is the detail of my code for the test:

Solution A:

```
 if (Connect(ftpIpAddress, ftpUserId, ftpPassword))
                {
if (FtpClient.DirectoryExists(folderPath))
                    {
 FtpClient.DeleteDirectory(folderPath);
}
}
```

Solution B:

 ```
 if (Connect(ftpIpAddress, ftpUserId, ftpPassword))
                {
if (FtpClient.DirectoryExists(folderPath))
                    {
Disconnect(ftpIpAddress);

                        Connect(ftpIpAddress);
 FtpClient.DeleteDirectory(folderPath);
}
}
```
I add also the FtpFluent logs

[SolutionA_withoutDisconnect.txt](https://github.com/hgupta9/FluentFTP/files/1018517/SolutionA_withoutDisconnect.txt)
[SolutionB_withDisconnect.txt](https://github.com/hgupta9/FluentFTP/files/1018520/SolutionB_withDisconnect.txt)


Please let me know what you recommend to resolve this issue.

**Comment by hgupta9** [comment] 2017-05-23 11:04
1. Try using passive mode - `client.DataConnectionType = FtpDataConnectionType.PASV`

2. Try using [this class](https://www.codeproject.com/articles/760521/ftp-from-windows-ce-devices) - not sure if it matches your use case

**Comment by pbindy** [comment] 2017-05-23 11:53
1. Can you explain what the passive mode activation does exactly?
2. Actually, before implementing FluentFtp library, the FTP transfer was done with the DLL FtpRequest. I'll check this TcpClient class.
3. When looking for a 3rd part library, I was between EDT FTP and FluentFTP but I liked FluentFTP more.

With those remarks, does it mean that the issue I'm facing will not be considered in FluentFTP?

**Comment by hgupta9** [comment] 2017-05-23 12:17
1. Some people have better success with Passive mode on Windows CE - Its a different type of FTP connection.
3. Can you try EDT to see if it resolves your issue? Then we can see if its an issue with FluentFTP implementation or issue with the FTP commands....

**Comment by pbindy** [comment] 2017-05-24 07:25
I tried passive mode, it doesn't change anything.

For now, I implemented as you suggested in a previous post. I use the Execute method and I reproduce exactly the commands that are done when doing the deleting from Filezilla. 

If this doesn't work 100%, I'll check 2 and 3 you mentioned.

Thanks

**Comment by hgupta9** [comment] 2017-05-25 10:50
Yes I think there is a difference in the way we call LIST command compared to Filezilla. Can you trace entire log of Filezilla including the LIST Command? Because the error happens after we LIST not after we DELE.

**Comment by hgupta9** [comment] 2017-06-04 07:28
I am closing this as no workable solution was found. I will reopen this issue if you wish to debug it further.

**Comment by pbindy** [comment] 2017-06-05 14:35
Ok for now. No solution found

**Comment by hgupta9** [comment] 2017-06-05 15:30
Hello! If you are back and have time to debug I would like to solve this issue!  Can you trace entire log of Filezilla including the LIST Command? Because the error happens after we LIST not after we DELE.

**Comment by pbindy** [comment] 2017-06-05 16:04
Ok I'll send you a trace tomorrow (Tuesday)

**Comment by pbindy** [comment] 2017-06-06 08:23
@hgupta9 
Here is the complete log file from Filezilla. I did a LIST of the folder and then delete it (it contains subdirectories and files)

Hope it helps...

[filezilla.txt](https://github.com/hgupta9/FluentFTP/files/1054241/filezilla.txt)

**Comment by pbindy** [comment] 2017-06-06 14:50
@hgupta9 Is it enough what I provided to you or you need more info ?

**Comment by hgupta9** [comment] 2017-06-06 15:05
Its good, thanks.

My first observation is FileZilla is using passive. So you need `client.DataConnectionType = FtpDataConnectionType.PASV`

Secondly I'm improving logging in FluentFTP so they can compare better with the FileZilla logs. Like adding prefix of "Command", "Response", etc.

Thirdly, I have to add logging for system command like PASV which are not logged. Therefore I cannot debug the actual part of data transfer. I will improve it and let you know.

**Comment by hgupta9** [comment] 2017-06-07 09:27
I have improved logging (see [here for sample](https://github.com/hgupta9/FluentFTP/issues/106#issuecomment-306739610)) and this should help us debug exactly where the problem is.

Can you download and test with this version? 

- [FluentFTP_17.4.3_BETA1.zip](https://we.tl/bBd6DBlJO5)

**Comment by pbindy** [comment] 2017-06-07 09:59
Here are 2 attempts I made to delete a directory with content.

I'm using Passive connection with
`       DataConnectionType = FtpDataConnectionType.PASV       `

Hope it helps
[fluentFtpLogFile_try1.txt](https://github.com/hgupta9/FluentFTP/files/1057624/fluentFtpLogFile_try1.txt)
[fluentFtpLogFile_try2.txt](https://github.com/hgupta9/FluentFTP/files/1057625/fluentFtpLogFile_try2.txt)

**Comment by hgupta9** [comment] 2017-06-07 15:20
Its very clear now. 
See the main difference between FluentFTP and Filezilla is:

Filezilla:

> Status: Retrieving directory listing of "/NANDFlash/sca3"...
> Command: PASV
> Response: 227 Entering Passive Mode (192,168,85,99,193,28).
> Command: LIST
> **Response: 125 Data connection already open; transfer starting.**
> **Response: 226 Closing data connection.** 
> Status: Directory listing of "/NANDFlash/sca3" successful

FluentFTP on WinCE:

> GetListing("/NANDFlash/sca3", ForceList, Recursive)
> Command:  TYPE I
> Response: 200 Command okay.
> Command:  PASV
> Response: 227 Entering Passive Mode (192,168,85,99,192,210).
> Status:   Connecting to 192.168.85.99:49362
> Command:  LIST -R /NANDFlash/sca3
> **Response: 125 Data connection already open; transfer starting.**
> **Response: 450 File unavailable (e.g., file busy).**

FluentFTP on unix server:

> GetListing("/public_html/temp/", ForceList, Recursive)
> Command:  TYPE I
> Response: 200 TYPE is now 8-bit binary
> Command:  EPSV
> Response: 229 Extended Passive mode OK (|||31051|)
> Status:   Connecting to ***:31051
> Command:  LIST -R /public_html/temp
> **Response: 150 Accepted data connection**

Can you do some more tests so I can verify whats happening:

**Test 1** - Just check if GetListing is working.
```
ftp.Connect()
ftp.GetListing("/NANDFlash/sca3")
ftp.GetListing("/NANDFlash/sca3")
ftp.Disconnect()
```

**Test 2** - Do the whole test but don't use recursive GetListing()
```
ftp.Connect()
ftp.DeleteDirectory("/NANDFlash/sca3", FtpListOption.ForceList) << ForceList prevents recursive
ftp.Disconnect()
```

Thanks.

**Comment by pbindy** [comment] 2017-06-08 06:21
Here are the logs of the tests you asked with the BETA3 version

> Test 1 - Just check if GetListing is working.
> 
> ftp.Connect()
> ftp.GetListing("/NANDFlash/sca3")
> ftp.GetListing("/NANDFlash/sca3")
> ftp.Disconnect()
> 
[fluentFtpLogFileTest1.txt](https://github.com/hgupta9/FluentFTP/files/1060076/fluentFtpLogFileTest1.txt)

> Test 2 - Do the whole test but don't use recursive GetListing()
> 
> ftp.Connect()
> ftp.DeleteDirectory("/NANDFlash/sca3", FtpListOption.ForceList) << ForceList prevents recursive
> ftp.Disconnect()

[fluentFtpLogFileTest2.txt](https://github.com/hgupta9/FluentFTP/files/1060077/fluentFtpLogFileTest2.txt)

**Comment by hgupta9** [comment] 2017-06-08 07:42
Thanks for that. I see what could be a bug in DeleteDirectory() .. Even though you have specified ForceList still it is using:

> GetListing("/NANDFlash/sca3", **ForceList, Recursive**)
> Command:  LIST -R /NANDFlash/sca3

Instead of the GetListing() which works for you:

> GetListing("/NANDFlash/sca3", **0**)
> Command: LIST /NANDFlash/sca3

----------------

Fixed that bug in DeleteDirectory(), also added new mode "Auto". Please use:
- [FluentFTP_17.4.3_BETA4.zip](https://we.tl/T8c3mkLZLq)

Can you please try:

**Test 3**
```
ftp.Connect()
ftp.DeleteDirectory("/NANDFlash/sca3", FtpListOption.Auto)
ftp.Disconnect()
```

**Test 4**
```
ftp.Connect()
ftp.DeleteDirectory("/NANDFlash/sca3", FtpListOption.ForceList)
ftp.Disconnect()
```

**Comment by pbindy** [comment] 2017-06-08 08:45
Looks good. Both ForceList and Auto are deleting the folder sca3.

[fluentFtpLogFileTest3.txt](https://github.com/hgupta9/FluentFTP/files/1060382/fluentFtpLogFileTest3.txt)
[fluentFtpLogFileTest4.txt](https://github.com/hgupta9/FluentFTP/files/1060381/fluentFtpLogFileTest4.txt)

Can you tell me more about those 2 options ?

**Comment by hgupta9** [comment] 2017-06-08 12:07
Fantastic! That's a relief. **I'll modify the lib to use "Auto" as default for Windows CE so future users won't have this problem.** The bug here was that Windows CE does not like "LIST -R" (recursive mode) which is why GetListing() was working but DeleteDirectory() was failing. You see, DeleteDirectory internally calls GetListing() with recursive ON, while just calling GetListing() has recursive OFF by default.

About the options:
- `Auto` - Don't use "recursive" (LIST -R) when asking server for files. If you specify nothing (like `GetListing(dir)`) then we use `ForceList | Recursive` as default. This is because recursive LIST is faster than doing multiple LIST commands when you want to delete a full directory recursively.
- `ForceList` - Forces using the LIST command instead of machine listings.

As you can probably tell, **both options effectively work the same** on Windows CE:
- `Auto` - machine listings not supported on Windows CE, so LIST command is used. Recursive off.
- `ForceList` - LIST command should be used. Recursive off.

**Closed** 2017-06-08 12:17 UTC
Labels: bug, windows-ce, work in progress

**Comment by pbindy** [comment] 2017-06-08 12:18
That's great! Thank you very much and well done!

Therefore, in my case I can use either Auto or ForceList, it doesn't make any real difference right?

When do you plan to make an official release with those changes?

**Comment by hgupta9** [comment] 2017-06-08 12:20
Done. https://www.nuget.org/packages/FluentFTP/17.4.3

If you use the new version it will auto detect Windows CE so you can just call DeleteDirectory() plainly and it should use the right option. Can you check it?

And enjoy!

**Comment by hgupta9** [comment] 2017-06-08 12:23
Thank for you helping me debug this and kindly running all tests required. In the process we improved the log quality so debugging future issues should be much easier.

**Comment by hgupta9** [comment] 2017-06-08 12:33
Oh no I forget to update something in DeleteDirectory(). Made another nuget release. Please use that.

https://www.nuget.org/packages/FluentFTP/17.4.4

**Comment by pbindy** [comment] 2017-06-08 12:42
Thanks I'll check this new version 17.4.4 and inform you of the result.
