### ISSUE TITLE
STOR Command not working with destination FTP

### ISSUE THREAD

**Issue by ggiaquin16** [hgupta9/FluentFTP#20] opened 2016-12-12 20:59 UTC
hello!  I am trying to submit a plain text file from my PC to an MVS MainFrame.  When attempting to put in the destination path for the openwrite, it times out on me.  doing this manually through the cmd prompt, the put command works just fine and the data is transmitted.  My destination path is written in MVS format EX: xxx.xxx.xxx.xxx and I have it surrounded by single quotes to take the string literally.  Am I doing something wrong?  Is this an issue with going to a mainframe with fluentftp?  Is this an issue on their end?

![image](https://cloud.githubusercontent.com/assets/24532233/21120304/db27441e-c083-11e6-81b2-8f3d92f6da79.png)

**Comment by ggiaquin16** [comment] 2016-12-13 21:47
Any updates or feedback?  I can't seem to get the upload to work and I have tried many variations of how to upload through FluentFTP all ending with the same issue.

**Comment by Zoltan666** [comment] 2016-12-13 22:16
The way I tracked down our problems was by using FileZilla to upload a file and examining the conversation between the client and the FTP server.

I used Wireshark to examine the conversation between FluentFTP and the server.

If you can upload both of those logs, it would be a start to figuring out what the problem is.

**Comment by ggiaquin16** [comment] 2016-12-13 22:20
For Wireshark, I haven't used it before, what do I put in for the capture filter?  the host address?

**Comment by Zoltan666** [comment] 2016-12-13 22:25
I think I put "http | ftp" (no quotes). You might just need "ftp".

**Comment by ggiaquin16** [comment] 2016-12-13 22:28
Ok thanks :) I will need to play around with these tools.  I probably won't have the logs ready until tomorrow!  My first time using either so apologize for any delay or issues with the tools.

**Comment by ggiaquin16** [comment] 2016-12-13 22:34
Status:	Starting upload of C:\Users\GXG1ISG\Desktop\VisualStudioRepository\NorthCarolinaDMVNEW\NCDMV\bin\Debug\Files\OutBound\DOTT.MVI.PRODBS.CLTR.INBCD.R28
Status:	Retrieving directory listing of "'TPY0R28.'"...
Command:	TYPE I
Response:	200 Representation type is Image
Command:	PASV
Response:	227 Entering Passive Mode (207,192,33,30,195,117)
Command:	LIST
Response:	550 No data sets found.
Command:	PASV
Response:	227 Entering Passive Mode (207,192,33,30,195,102)
Command:	STOR DOTT.MVI.PRODBS.CLTR.INBCD.R28
Error:	The data connection could not be established: ECONNREFUSED - Connection refused by server

**Comment by ggiaquin16** [comment] 2016-12-13 22:54
ok, here is a better log with more similar commands to what i am doing in fluent.

Status:	Resolving address of sccftp.its.state.nc.us
Status:	Connecting to 207.192.50.170:21...
Status:	Connection established, waiting for welcome message...
Status:	Initializing TLS...
Status:	Verifying certificate...
Status:	TLS connection established.
Status:	Logged in
Status:	Starting upload of C:\Users\GXG1ISG\Desktop\VisualStudioRepository\NorthCarolinaDMVNEW\NCDMV\bin\Debug\Files\OutBound\DOTT.MVI.PRODBS.CLTR.INBCD.R28
Status:	Retrieving directory listing of "'TPY0R28.'"...
Command:	TYPE I
Response:	200 Representation type is Image
Command:	PORT 172,31,130,109,195,210
Response:	200 Port request OK.
Command:	LIST
Response:	550 No data sets found.
Command:	TYPE A
Response:	200 Representation type is Ascii NonPrint
Command:	PORT 172,31,130,109,195,211
Response:	200 Port request OK.
Command:	STOR DOTT.MVI.PRODBS.CLTR.INBCD.R28
Error:	Connection timed out after 20 seconds of inactivity
Error:	File transfer failed

**Comment by Zoltan666** [comment] 2016-12-13 23:43
OK, I'm no expert, but it looks like the server is refusing the connection.

Are you able to upload successfully with FileZilla? If not, you'll need to address that with your network administrator.

**Comment by hgupta9** [comment] 2016-12-14 05:24
Both logs that you sent are of the failure. Can you send a successful transfer log (via Filezilla + Wireshark) so we can compare and see what Filezilla is doing right?

**Comment by ggiaquin16** [comment] 2016-12-14 15:21
Well that is the issue and zoltan you are probably right.  I just find it odd though that I am able to log in and connect to the server, but it does not do a file upload.  The only way for me to get a successful file load is if I manually do the commands through cmd prompt and do the transfer with PUT.  I cannot successfully upload through filezilla or my application.

**Comment by ggiaquin16** [comment] 2016-12-14 15:29
Also, not sure if this helps but maybe this may be part of the issue? This was part of the documentation for the project:

2) Please verify that your FTPS software can process Port Command Format 2, or ignore the IP address that is provided in Port Command Format 1.

**Comment by Zoltan666** [comment] 2016-12-14 15:55
OK, can you get us a Wireshark log of the conversation with the FTP server when you execute a PUT command in your cmd prompt FTP client? If you could, send the entire conversation from login to successful upload. Remove any sensitive information (e.g. username/password).
Note that PUT is the user-friendly command, it will likely send a STOR to the server.

**Comment by ggiaquin16** [comment] 2016-12-14 16:01
Yes :) STOR is part of the command sequence in a PUT :)  I did a whole bunch of research on that haha I am still trying to understand wireshark.  When you say log what do you mean exactly? are you talking about the pcap?

**Comment by ggiaquin16** [comment] 2016-12-14 16:29
![wiresharklog](https://cloud.githubusercontent.com/assets/24532233/21190660/c8a5fbc0-c1df-11e6-9a78-f01c56d23167.PNG)

**Comment by Zoltan666** [comment] 2016-12-14 16:36
I see your screenshot. Just for reference... :-)

Here's the sequence I follow:
1. Start Wireshark
2. Double click Ethernet on the opening page. This will start the capture
3. Add a Display Filter "ftp || ftp-data" (no quotes)
4. Do the FTP upload
5. Capture->Stop
6. Edit->Mark All Displayed
7. File->Export Packet Dissections ->As Plain Text-
  Select 
  - Marked Packets
  - Packet summary line
  Unselect
  - Packet details

8. Edit the file to remove any sensitive data

**Comment by ggiaquin16** [comment] 2016-12-14 16:38
This looks like it could be an authentication issue.  One thing I noticed in my cmd Prompt was that there was no TLS acknowledgement.  I went to go do cmd prompt again submitting auth TLS and shortly after it says connection closed by remote host.

**Comment by Zoltan666** [comment] 2016-12-14 16:40
There's also no mention of passive mode.

**Comment by ggiaquin16** [comment] 2016-12-14 16:40
When I tried to do it passive, in both filezilla and my application, it gave me the error you saw above about connection refused by host.

**Comment by Zoltan666** [comment] 2016-12-14 16:45
Yes, try FileZilla in Active transfer mode and turn off any encryption.

**Comment by ggiaquin16** [comment] 2016-12-14 16:52
[NCDMVWireSharkCmdPrompt.txt](https://github.com/hgupta9/FluentFTP/files/652300/NCDMVWireSharkCmdPrompt.txt)

**Comment by ggiaquin16** [comment] 2016-12-14 16:55
Status:	Resolving address of sccftp.its.state.nc.us
Status:	Connecting to 207.192.50.170:991...
Status:	Connection established, waiting for welcome message...
Response:	220-FTP 11:55:22 on 2016-12-14.
Response:	220-                          Warning!
Response:	220- This is a government Computer System and is the property of the
Response:	220-State of North Carolina. Users have no expectation of privacy. Use
Response:	220- of this computer system is subject to monitoring or other review
Response:	220-  by the government operator or others. Unauthorized or improper
Response:	220-use of this system may result in administrative disciplinary action
Response:	220-               and civil and criminal penalties.
Response:	220-
Response:	220-      Use of this system constitutes consent to monitoring.
Response:	220 Connection will close if idle for more than 5 minutes.
Command:	USER tpy0r28
Response:	534 Server requires authentication before USER command
Error:	Could not connect to server

**Comment by Zoltan666** [comment] 2016-12-14 17:02
OK, what does it do with the authentication on?

**Comment by ggiaquin16** [comment] 2016-12-14 17:05
Status:	Resolving address of sccftp.its.state.nc.us
Status:	Connecting to 207.192.50.170:21...
Status:	Connection established, waiting for welcome message...
Status:	Initializing TLS...
Status:	Verifying certificate...
Status:	TLS connection established.
Status:	Logged in
Status:	Retrieving directory listing...
Status:	Directory listing of "'TPY0R28.'" successful

**Comment by Zoltan666** [comment] 2016-12-14 17:27
And with the file upload?

**Comment by ggiaquin16** [comment] 2016-12-14 17:30
Status:	Resolving address of sccftp.its.state.nc.us
Status:	Connecting to 207.192.50.170:21...
Status:	Connection established, waiting for welcome message...
Status:	Initializing TLS...
Status:	Verifying certificate...
Status:	TLS connection established.
Status:	Logged in
Status:	Starting upload of C:\Users\GXG1ISG\Desktop\VisualStudioRepository\NorthCarolinaDMVNEW\NCDMV\bin\Debug\Files\OutBound\DOTT.MVI.PRODBS.CLTR.INBCD.R28
Command:	CWD 'TPY0R28.'
Response:	250 "TPY0R28." is the working directory name prefix.
Command:	PWD
Response:	257 "'TPY0R28.'" is working directory.
Command:	TYPE A
Response:	200 Representation type is Ascii NonPrint
Command:	PORT 172,31,130,109,225,72
Response:	200 Port request OK.
Command:	STOR DOTT.MVI.PRODBS.CLTR.INBCD.R28
Error:	Connection timed out after 20 seconds of inactivity
Error:	File transfer failed
Status:	Disconnected from server

**Comment by Zoltan666** [comment] 2016-12-14 17:33
Can you post the Wireshark log for this interaction?

**Comment by ggiaquin16** [comment] 2016-12-14 17:39
[NCDMVWireSharkFileZilla.txt](https://github.com/hgupta9/FluentFTP/files/652408/NCDMVWireSharkFileZilla.txt)

**Comment by Zoltan666** [comment] 2016-12-14 17:44
And that's all encrypted. Ha!

I did notice this in your cmd prompt log:

Request: site recfm=fb lrecl=380 blksize=27740

This looks like an IBM specific command. Which FTP program are you using at the command prompt?

**Comment by ggiaquin16** [comment] 2016-12-14 17:45
I just type in ftp into command prompt to open it up.

**Comment by Zoltan666** [comment] 2016-12-14 17:56
Have you tried setting the server type to "MVS, OS/390, z/OS" in FileZilla?

**Comment by ggiaquin16** [comment] 2016-12-14 17:59
It was on auto detect but I will explicitly have it as MVS and see if that changes anything.  Yea no change.  Same thing.

**Comment by Zoltan666** [comment] 2016-12-14 18:24
OK, let's try a different tack. In FileZilla, go to Edit->Settings->Debug and set the debug level to Verbose.

Try the upload again and post the FileZilla log here.

**Comment by ggiaquin16** [comment] 2016-12-14 20:47
Sorry was at a work lunch posting it now :)

Status:	Resolving address of sccftp.its.state.nc.us
Status:	Connecting to 207.192.50.170:21...
Status:	Connection established, waiting for welcome message...
Trace:	CFtpControlSocket::OnReceive()
Response:	220-FTP 15:46:33 on 2016-12-14.
Response:	220-                          Warning!
Trace:	CFtpControlSocket::OnReceive()
Response:	220- This is a government Computer System and is the property of the
Response:	220-State of North Carolina. Users have no expectation of privacy. Use
Response:	220- of this computer system is subject to monitoring or other review
Response:	220-  by the government operator or others. Unauthorized or improper
Response:	220-use of this system may result in administrative disciplinary action
Response:	220-               and civil and criminal penalties.
Response:	220-
Response:	220-      Use of this system constitutes consent to monitoring.
Response:	220 Connection will close if idle for more than 5 minutes.
Trace:	CFtpControlSocket::SendNextCommand()
Command:	AUTH TLS
Trace:	CFtpControlSocket::OnReceive()
Response:	234 Security environment established - ready for negotiation
Status:	Initializing TLS...
Trace:	CTlsSocket::Handshake()
Trace:	CTlsSocket::ContinueHandshake()
Trace:	CTlsSocket::ContinueHandshake()
Trace:	CTlsSocket::ContinueHandshake()
Trace:	CTlsSocket::ContinueHandshake()
Trace:	TLS Handshake successful
Trace:	Protocol: TLS1.0, Key exchange: RSA, Cipher: AES-256-CBC, MAC: SHA1
Status:	Verifying certificate...
Status:	TLS connection established.
Trace:	CFtpControlSocket::SendNextCommand()
Command:	USER tpy0r28
Trace:	CFtpControlSocket::OnReceive()
Response:	331 Send password please.
Trace:	CFtpControlSocket::SendNextCommand()
Command:	PASS ********
Trace:	CFtpControlSocket::OnReceive()
Response:	230 TPY0R28 is logged on.  Working directory is "TPY0R28.".
Trace:	CFtpControlSocket::SendNextCommand()
Command:	OPTS UTF8 ON
Trace:	CFtpControlSocket::OnReceive()
Response:	501 command OPTS aborted -- no options supported for UTF8
Trace:	CFtpControlSocket::SendNextCommand()
Command:	PBSZ 0
Trace:	CFtpControlSocket::OnReceive()
Response:	200 Protection buffer size accepted
Trace:	CFtpControlSocket::SendNextCommand()
Command:	PROT P
Trace:	CFtpControlSocket::OnReceive()
Response:	200 Data connection protection set to private
Status:	Logged in
Trace:	CFtpControlSocket::ResetOperation(0)
Trace:	CControlSocket::ResetOperation(0)
Trace:	Measured latency of 102 ms
Trace:	CFtpControlSocket::FileTransfer()
Status:	Starting upload of C:\Users\GXG1ISG\Desktop\VisualStudioRepository\NorthCarolinaDMVNEW\NCDMV\bin\Debug\Files\OutBound\DOTT.MVI.PRODBS.CLTR.INBCD.R28
Trace:	CFtpControlSocket::SendNextCommand()
Trace:	CFtpControlSocket::ChangeDirSend()
Command:	CWD 'TPY0R28.'
Trace:	CFtpControlSocket::OnReceive()
Response:	250 "TPY0R28." is the working directory name prefix.
Trace:	CFtpControlSocket::ResetOperation(0)
Trace:	CControlSocket::ResetOperation(0)
Trace:	CFtpControlSocket::ParseSubcommandResult(0)
Trace:	FileTransferSubcommandResult()
Status:	Retrieving directory listing of "'TPY0R28.'"...
Trace:	ftpcontrolsocket.cpp(1350): List called from other command   caller=0x3901dd0
Trace:	CFtpControlSocket::ParseSubcommandResult(0)
Trace:	CFtpControlSocket::ListSubcommandResult()
Trace:	CFtpControlSocket::SendNextCommand()
Trace:	CFtpControlSocket::TransferSend()
Command:	TYPE I
Trace:	CFtpControlSocket::OnReceive()
Response:	200 Representation type is Image
Trace:	CFtpControlSocket::TransferParseResponse()
Trace:	CFtpControlSocket::SendNextCommand()
Trace:	CFtpControlSocket::TransferSend()
Command:	PORT 172,31,130,109,231,3
Trace:	CFtpControlSocket::OnReceive()
Response:	200 Port request OK.
Trace:	CFtpControlSocket::TransferParseResponse()
Trace:	CFtpControlSocket::SendNextCommand()
Trace:	CFtpControlSocket::TransferSend()
Command:	LIST
Trace:	CFtpControlSocket::OnReceive()
Response:	550 No data sets found.
Trace:	CFtpControlSocket::TransferParseResponse()
Trace:	CFtpControlSocket::ResetOperation(2)
Trace:	CControlSocket::ResetOperation(2)
Trace:	CFtpControlSocket::ParseSubcommandResult(2)
Trace:	CFtpControlSocket::ListSubcommandResult()
Trace:	CFtpControlSocket::ResetOperation(0)
Trace:	CControlSocket::ResetOperation(0)
Trace:	CFtpControlSocket::ParseSubcommandResult(0)
Trace:	FileTransferSubcommandResult()
Trace:	CFtpControlSocket::SendNextCommand()
Trace:	FileTransferSend()
Trace:	CFtpControlSocket::SendNextCommand()
Trace:	CFtpControlSocket::TransferSend()
Command:	TYPE A
Trace:	CFtpControlSocket::OnReceive()
Response:	200 Representation type is Ascii NonPrint
Trace:	CFtpControlSocket::TransferParseResponse()
Trace:	CFtpControlSocket::SendNextCommand()
Trace:	CFtpControlSocket::TransferSend()
Command:	PORT 172,31,130,109,231,4
Trace:	CFtpControlSocket::OnReceive()
Response:	200 Port request OK.
Trace:	CFtpControlSocket::TransferParseResponse()
Trace:	CFtpControlSocket::SendNextCommand()
Trace:	CFtpControlSocket::TransferSend()
Command:	STOR DOTT.MVI.PRODBS.CLTR.INBCD.R28
Status:	Disconnected from server
Trace:	CFtpControlSocket::ResetOperation(66)
Trace:	CControlSocket::ResetOperation(66)
Error:	Connection timed out after 20 seconds of inactivity
Trace:	CFtpControlSocket::ResetOperation(2114)
Trace:	CControlSocket::ResetOperation(2114)
Trace:	CFtpControlSocket::ResetOperation(2114)
Trace:	CControlSocket::ResetOperation(2114)
Error:	File transfer failed

**Comment by Zoltan666** [comment] 2016-12-14 21:14
>>This looks like an IBM specific command.
> that site command is also specifically requested by them.

I missed this detail earlier. After connecting in FileZilla, go to Server->Enter custom command
site recfm=fb lrecl=380 blksize=27740

**Comment by ggiaquin16** [comment] 2016-12-14 21:38
Status:	Resolving address of sccftp.its.state.nc.us
Status:	Connecting to 207.192.50.170:21...
Status:	Connection established, waiting for welcome message...
Trace:	CFtpControlSocket::OnReceive()
Response:	220-FTP 16:37:13 on 2016-12-14.
Response:	220-                          Warning!
Trace:	CFtpControlSocket::OnReceive()
Response:	220- This is a government Computer System and is the property of the
Response:	220-State of North Carolina. Users have no expectation of privacy. Use
Response:	220- of this computer system is subject to monitoring or other review
Response:	220-  by the government operator or others. Unauthorized or improper
Response:	220-use of this system may result in administrative disciplinary action
Response:	220-               and civil and criminal penalties.
Response:	220-
Response:	220-      Use of this system constitutes consent to monitoring.
Response:	220 Connection will close if idle for more than 5 minutes.
Trace:	CFtpControlSocket::SendNextCommand()
Command:	AUTH TLS
Trace:	CFtpControlSocket::OnReceive()
Response:	234 Security environment established - ready for negotiation
Status:	Initializing TLS...
Trace:	CTlsSocket::Handshake()
Trace:	CTlsSocket::ContinueHandshake()
Trace:	CTlsSocket::ContinueHandshake()
Trace:	CTlsSocket::ContinueHandshake()
Trace:	CTlsSocket::ContinueHandshake()
Trace:	TLS Handshake successful
Trace:	Protocol: TLS1.0, Key exchange: RSA, Cipher: AES-256-CBC, MAC: SHA1
Status:	Verifying certificate...
Status:	TLS connection established.
Trace:	CFtpControlSocket::SendNextCommand()
Command:	USER tpy0r28
Trace:	CFtpControlSocket::OnReceive()
Response:	331 Send password please.
Trace:	CFtpControlSocket::SendNextCommand()
Command:	PASS ********
Trace:	CFtpControlSocket::OnReceive()
Response:	230 TPY0R28 is logged on.  Working directory is "TPY0R28.".
Trace:	CFtpControlSocket::SendNextCommand()
Command:	OPTS UTF8 ON
Trace:	CFtpControlSocket::OnReceive()
Response:	501 command OPTS aborted -- no options supported for UTF8
Trace:	CFtpControlSocket::SendNextCommand()
Command:	PBSZ 0
Trace:	CFtpControlSocket::OnReceive()
Response:	200 Protection buffer size accepted
Trace:	CFtpControlSocket::SendNextCommand()
Command:	PROT P
Trace:	CFtpControlSocket::OnReceive()
Response:	200 Data connection protection set to private
Status:	Logged in
Trace:	CFtpControlSocket::ResetOperation(0)
Trace:	CControlSocket::ResetOperation(0)
Trace:	Measured latency of 93 ms
Trace:	CFtpControlSocket::FileTransfer()
Status:	Starting upload of C:\Users\GXG1ISG\Desktop\VisualStudioRepository\NorthCarolinaDMVNEW\NCDMV\bin\Debug\Files\OutBound\DOTT.MVI.PRODBS.CLTR.INBCD.R28
Trace:	CFtpControlSocket::SendNextCommand()
Trace:	CFtpControlSocket::ChangeDirSend()
Command:	CWD 'TPY0R28.'
Trace:	CFtpControlSocket::OnReceive()
Response:	250 "TPY0R28." is the working directory name prefix.
Trace:	CFtpControlSocket::ResetOperation(0)
Trace:	CControlSocket::ResetOperation(0)
Trace:	CFtpControlSocket::ParseSubcommandResult(0)
Trace:	FileTransferSubcommandResult()
Status:	Retrieving directory listing of "'TPY0R28.'"...
Trace:	ftpcontrolsocket.cpp(1350): List called from other command   caller=0x3901dd0
Trace:	CFtpControlSocket::ParseSubcommandResult(0)
Trace:	CFtpControlSocket::ListSubcommandResult()
Trace:	CFtpControlSocket::SendNextCommand()
Trace:	CFtpControlSocket::TransferSend()
Command:	TYPE I
Trace:	CFtpControlSocket::OnReceive()
Response:	200 Representation type is Image
Trace:	CFtpControlSocket::TransferParseResponse()
Trace:	CFtpControlSocket::SendNextCommand()
Trace:	CFtpControlSocket::TransferSend()
Command:	PORT 172,31,130,109,232,193
Trace:	CFtpControlSocket::OnReceive()
Response:	200 Port request OK.
Trace:	CFtpControlSocket::TransferParseResponse()
Trace:	CFtpControlSocket::SendNextCommand()
Trace:	CFtpControlSocket::TransferSend()
Command:	LIST
Trace:	CFtpControlSocket::OnReceive()
Response:	550 No data sets found.
Trace:	CFtpControlSocket::TransferParseResponse()
Trace:	CFtpControlSocket::ResetOperation(2)
Trace:	CControlSocket::ResetOperation(2)
Trace:	CFtpControlSocket::ParseSubcommandResult(2)
Trace:	CFtpControlSocket::ListSubcommandResult()
Trace:	CFtpControlSocket::ResetOperation(0)
Trace:	CControlSocket::ResetOperation(0)
Trace:	CFtpControlSocket::ParseSubcommandResult(0)
Trace:	FileTransferSubcommandResult()
Trace:	CFtpControlSocket::SendNextCommand()
Trace:	FileTransferSend()
Trace:	CFtpControlSocket::SendNextCommand()
Trace:	CFtpControlSocket::TransferSend()
Command:	TYPE A
Trace:	CFtpControlSocket::OnReceive()
Response:	200 Representation type is Ascii NonPrint
Trace:	CFtpControlSocket::TransferParseResponse()
Trace:	CFtpControlSocket::SendNextCommand()
Trace:	CFtpControlSocket::TransferSend()
Command:	PORT 172,31,130,109,232,194
Trace:	CFtpControlSocket::OnReceive()
Response:	200 Port request OK.
Trace:	CFtpControlSocket::TransferParseResponse()
Trace:	CFtpControlSocket::SendNextCommand()
Trace:	CFtpControlSocket::TransferSend()
Command:	STOR DOTT.MVI.PRODBS.CLTR.INBCD.R28
Error:	Connection timed out after 20 seconds of inactivity
Trace:	CFtpControlSocket::ResetOperation(2114)
Trace:	CControlSocket::ResetOperation(2114)
Trace:	CFtpControlSocket::ResetOperation(2114)
Trace:	CControlSocket::ResetOperation(2114)
Error:	File transfer failed

**Comment by Zoltan666** [comment] 2016-12-14 21:59
I don't see the site command in that log.

**Comment by ggiaquin16** [comment] 2016-12-14 22:14
Command:	site recfm=fb lrecl=380 blksize=27740
Trace:	CFtpControlSocket::OnReceive()
Response:	200 SITE command was accepted
Trace:	CFtpControlSocket::RawCommandParseResponse
Trace:	CFtpControlSocket::ResetOperation(0)
Trace:	CControlSocket::ResetOperation(0)
Status:	Disconnected from server
is where it is

**Comment by Zoltan666** [comment] 2016-12-14 22:31
Can you post the cmd prompt commands that you use to successfully transfer the file? Also are you specifying a remote path like this? https://forum.filezilla-project.org/viewtopic.php?t=41382

**Comment by ggiaquin16** [comment] 2016-12-14 22:35
Yes I am doing it with the single quote to enforce literal string and with the dots as specified.  
For cmd Prompt, I do the following:
ftp
open sccftp.its.state.nc.us
prompted for username
prompted for password
quote site recfm=fb lrecl=380 blksize=27740
put  C:\Users\GXG1ISG\Desktop\VisualStudioRepository\NorthCarolinaDMVNEW\NCDMV\bin\Debug\Files\OutBound\DOTT.MVI.PRODBS.CLTR.INBCD.R28 'DOTT.MVI.PRODBS.CLTR.INBCD.R28'
after it sends I type bye.

**Comment by ggiaquin16** [comment] 2016-12-14 22:39
If i try to add quote auth tls it gives me an error saying remote path closed by host.

**Comment by Zoltan666** [comment] 2016-12-14 22:40
Try setting the remote directory in FileZilla to something with single quotes, and see if that causes it to send the STOR with quotes also.

**Comment by ggiaquin16** [comment] 2016-12-14 22:46
no such luck however I have tried adding the quotes in the application and I still got a time out.  Tried setting the remote directory to the file name which is their internal directory and it didn't like that.  Changed it to the working directory i know works and I got a stor command without quotes still.

**Comment by ggiaquin16** [comment] 2016-12-15 21:40
ok update.... IS there a way to do this?
"The address returned to you is not reachable by you.   If there is a parameter that says to ignore this address and continue with the original, you should select that." in filezilla or fluentftp?

**Comment by Zoltan666** [comment] 2016-12-15 22:00
Which address is that?

**Comment by ggiaquin16** [comment] 2016-12-15 22:18
He said that to me after seeing:

Command:        PASV

Trace:  CFtpControlSocket::OnReceive()

Response:       227 Entering Passive Mode (207,192,33,30,195,109)

Trace:  CFtpControlSocket::TransferParseResponse()

Trace:  CFtpControlSocket::SendNextCommand()

Trace:  CFtpControlSocket::TransferSend()

Trace:  Destination IP of data connection does not match peer IP of control connection. Not binding source address of data connection.

Command:        STOR DOTT.MVI.PRODBS.CLTR.INBCD.R28

Error:  The data connection could not be established: ECONNREFUSED - Connection refused by server

Trace:  CTransferSocket::TransferEnd(3)

Trace:  CFtpControlSocket::TransferEnd()

**Comment by Zoltan666** [comment] 2016-12-15 22:22
Your cmd prompt FTP session isn't using passive mode.

**Comment by ggiaquin16** [comment] 2016-12-15 22:24
No but the server admin I am working with told me to do passive mode. "You are using  active mode and your port command  specifies a different IP than what is in the log here for your ID.

 

Command:        PORT 172,31,130,109,207,169

 

This means this address is not reachable by me.   This command also specifies port  (256 x 207) + 169,  which might not be open on your firewall.

 

If you can specifiy  extended passive mode, and if your firewall is open for port range 50000 – 50040   this might go better."

**Comment by Zoltan666** [comment] 2016-12-15 22:54
Weird, the server was perfectly happy with this command from your FTP client: "Request: PORT 172,31,130,109,223,120"

Are you going through a proxy to get to this FTP site? You can determine this thusly: http://babel.jorgebg.com/configure-proxy-windows-7

**Comment by ggiaquin16** [comment] 2016-12-15 23:10
Nope no proxy set up based on the link you showed me.  ><

**Comment by ggiaquin16** [comment] 2016-12-16 03:26
Please verify that your FTPS software can process Port Command Format 2, or ignore the IP address that is provided in Port Command Format 1.

This was a part of the instructions to the project.  I tried googling this back then too and did so again a little tonight and still found nothing talking about port command formats.  Not sure what this means but I believe this has to do with what he is referring to in terms of ignoring the IP address.

**Comment by ggiaquin16** [comment] 2016-12-16 15:04
Port command format  2    (!!!50029)      No IP address is specified,  which means to use the ‘original’  IP address,  and the port  number is specified explicitly.   Format 2  is  for  ‘exteended passive mode’

do we have this ability in fluentFTP?

**Comment by Zoltan666** [comment] 2016-12-16 15:59
You can specify your external IP address like this: https://wiki.filezilla-project.org/Network_Configuration#Active_mode

**Comment by hgupta9** [comment] 2017-01-05 12:49
Are you done with this issue? Can I close it?

**Comment by ggiaquin16** [comment] 2017-01-05 16:39
It seems that this issue is not related to the library so you can go ahead and close it.  I am not done with it but as far as your end goes, I don't think there is anything more you guys can do on your end.  Thanks guys for the help in trying to solve this :)

**Comment by hgupta9** [comment] 2017-01-06 05:29
Thanks!

**Closed by hgupta9** 2017-01-06 05:29 UTC
