### ISSUE TITLE
GetObjectInfo Exception

### ISSUE THREAD

**Issue by lanopk** [hgupta9/FluentFTP#74] opened 2017-04-18 10:19 UTC
When I call `ftp.GetObjectInfo("/Temp");` this call raises Exception in the Fluent Ftp parsing routines.

Environments : Windows 10 Pro 64bit, Visual Studio 2015 Express, FluentFTP Nuget Package (v16.4.0)

Please check WinSCP Command Execute And Reply

```
MLST /Temp
250- Listing /Temp:
 type=dir;modify=20170418084826;size=444;UNIX.mode=0777;UNIX.owner=root;UNIX.group=root; Temp
250 End
```

**Comment by jblacker** [comment] 2017-05-04 14:51
What type of server are you attempting to connect to? Do any other functions work?  

Just to confirm I'm assuming that the bottom of your comment is the issued command and the "Please check WinSCP Command Execute and Reply" is the response from the server, correct?

I'm curious to the line referring to WinSCP, because this library doesn't support SCP (or any other SSH-based protocols).  If you're attempting to connect to an SCP or SFTP server you should use [SSH.NET](https://github.com/sshnet/SSH.NET) instead.

**Comment by hgupta9** [comment] 2017-05-04 16:06
Thank you @jblacker for kindly answering this question and providing your help.

**Comment by lanopk** [comment] 2017-05-05 16:34
Sorry my poor English.
Ftp Server is a Synology Network Device. This device support FTP, FTPS and WebDAV.
I did connect using FTPS (NOT SFTP).
GetObjectInfo function raise Exception and GetModifiedTime returns 0.
For test MLST command, run WinSCP windows ftp client program, connect Synology FTP Server, send command MLST /Temp, and get valid response. (above is command and response).
So, now, I did parse manually results of Execute("MLST /Temp"). and works good.

**Comment by jblacker** [comment] 2017-05-05 19:18
Ah it's just the parser that's throwing.  Hmm...i wonder why their formatting is different from the rest that are working.

**Comment by hgupta9** [comment] 2017-05-06 16:49
I've upgraded the GetListing() file listing parser to include OS-specific parsers. This may resolve your issue. If you are interested in helping debug this, then please use this beta build and give me feedback: 

- [FluentFTP_16.6_BETA.rar](https://we.tl/YiWHrDYJxq)

**Comment by lanopk** [comment] 2017-05-07 06:37
Thank you.
I download beta dll and test it.
GetObjectInfo function works fine.
But GetListing raise exception (string format exception).

   Location: System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   Location: System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   Location: System.String.Format(String format, Object[] args)
   Location: FluentFTP.FtpClient.GetListing(String path, FtpListOption options)

**Comment by hgupta9** [comment] 2017-05-07 07:37
Thanks. I need more info to debug your case. 

1. Can you trace the path your are calling GetListing() with
2. Can you show the line of code with GetListing()
3. Can you trace the working directory using GetWorkingDirectory()

**Comment by lanopk** [comment] 2017-05-07 16:24
Below is my code for GetPathList Function

===================================
Ftpftp ftp = new Ftpftp();
ftp.Host = ftpAddress;
ftp.Port = ftpPort;
ftp.Credentials = new NetworkCredential(ftpUserID, ftpPassword);

if (usePassive)
	ftp.DataConnectionType = FtpDataConnectionType.AutoPassive;
else
	ftp.DataConnectionType = FtpDataConnectionType.AutoActive;

if(lastEncoding == null)
	ftp.Encoding = Encoding.Default;
else
	ftp.Encoding = lastEncoding;

if (useSSL)
{
	ftp.EncryptionMode = FtpEncryptionMode.Explicit;
	ftp.ValidateCertificate += (control, e) => {
		e.Accept = true;
	};
}

ftp.UngracefullDisconnection = true;
string workingPath = ftp.GetWorkingDirectory(); // for test
FtpListItem[] list = ftp.GetListing(ftppath);
...

ftp.Disconnect();
ftp.Dispose();


(1) ftppath is "/" :
	GetWorkingDirectory returns "/".
	GetListing works fine.
(2) ftppath is "/Temp" :
	GetWorkingDirectory returns "/".
	GetListing raise Exception.


* Exception Info :
System.FormatException
  HResult=-2146233033
  Message=(Invalid Input String.... Korean Message)
  Source=mscorlib
  StackTrace:
       위치: System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
       위치: System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
       위치: System.String.Format(String format, Object[] args)
       위치: FluentFTP.FtpClient.GetListing(String path, FtpListOption options)
       위치: RaiDrive.Service.FTP.FtpAPI.GetFtpList(String path, Boolean& wantPassive) file C:\...\FtpAPI.cs:line 1053
  InnerException: 

* /Temp folder has some folder and files. some foldername/filename is Korean. (UTF-8)

**Comment by hgupta9** [comment] 2017-05-07 16:49
Can you try this and see if it works for you?

- [FluentFTP_16.6_BETA2.zip](https://we.tl/obsfya0qtl)

**Comment by lanopk** [comment] 2017-05-07 17:36
16.6 Beta2 raise same exception.
below is winscp ftp client log.

< 2017-05-08 02:26:26.465 230 User lanopk logged in.
> 2017-05-08 02:26:26.465 SYST
< 2017-05-08 02:26:26.675 215 UNIX Type: L8
> 2017-05-08 02:26:26.675 FEAT
< 2017-05-08 02:26:26.695 211- Extensions supported:
< 2017-05-08 02:26:26.695  AUTH TLS
< 2017-05-08 02:26:26.705  PBSZ
< 2017-05-08 02:26:26.705  PROT
< 2017-05-08 02:26:26.705  SIZE
< 2017-05-08 02:26:26.705  MDTM
< 2017-05-08 02:26:26.705  MFMT
< 2017-05-08 02:26:26.705  REST STREAM
< 2017-05-08 02:26:26.705  UTF8
< 2017-05-08 02:26:26.705  MLST type*;modify*;size*;UNIX.mode*;UNIX.owner*;UNIX.group*;
< 2017-05-08 02:26:26.745  MLSD
< 2017-05-08 02:26:26.745 211 End.
> 2017-05-08 02:26:26.745 OPTS UTF8 ON
< 2017-05-08 02:26:26.895 200 OK, UTF-8 enabled
> 2017-05-08 02:26:26.895 PBSZ 0
< 2017-05-08 02:26:26.905 200 PBSZ command successful (PBSZ=0).
> 2017-05-08 02:26:26.905 PROT P
< 2017-05-08 02:26:26.925 200 Protection level set to Private.
. 2017-05-08 02:26:26.935 Got reply 1 to the command 1
. 2017-05-08 02:26:26.935 --------------------------------------------------------------------------
. 2017-05-08 02:26:26.935 Using FTP protocol.
. 2017-05-08 02:26:26.935 Doing startup conversation with host.
> 2017-05-08 02:26:26.985 PWD
< 2017-05-08 02:26:27.105 257 "/" is current directory.
. 2017-05-08 02:26:27.105 Got reply 1 to the command 16
. 2017-05-08 02:26:27.105 Changing directory to "/".
> 2017-05-08 02:26:27.105 CWD /
< 2017-05-08 02:26:27.285 250 CWD command successful.
. 2017-05-08 02:26:27.285 Got reply 1 to the command 16
. 2017-05-08 02:26:27.285 Getting current directory name.
> 2017-05-08 02:26:27.285 PWD
< 2017-05-08 02:26:27.345 257 "/" is current directory.
. 2017-05-08 02:26:27.345 Got reply 1 to the command 16
> 2017-05-08 02:26:27.485 TYPE A
< 2017-05-08 02:26:27.515 200 Type set to A.
> 2017-05-08 02:26:27.515 PASV
< 2017-05-08 02:26:27.535 227 Entering Passive Mode (192,168,200,40,216,246)
. 2017-05-08 02:26:27.535 Server sent passive reply with unroutable address 192.168.200.40, using host address instead.
> 2017-05-08 02:26:27.535 MLSD
< 2017-05-08 02:26:27.565 150 Opening BINARY mode SSL data connection for 'file list'.
. 2017-05-08 02:26:27.565 Session ID reused
. 2017-05-08 02:26:27.565 Using TLSv1.2, cipher TLSv1/SSLv3: AES256-GCM-SHA384, 2048 bit RSA, AES256-GCM-SHA384       TLSv1.2 Kx=RSA      Au=RSA  Enc=AESGCM(256) Mac=AEAD
. 2017-05-08 02:26:27.565 Session upkeep
< 2017-05-08 02:26:27.695 226 Transfer complete.
. 2017-05-08 02:26:27.735 Data connection closed
. 2017-05-08 02:26:27.735 type=dir;modify=20170228065625;size=122;UNIX.mode=0755;UNIX.owner=root;UNIX.group=users; home
. 2017-05-08 02:26:27.735 type=dir;modify=20170214145911;size=48;UNIX.mode=0755;UNIX.owner=root;UNIX.group=users; Waiting
. 2017-05-08 02:26:27.735 type=dir;modify=20170226022926;size=52;UNIX.mode=0755;UNIX.owner=root;UNIX.group=users; Utilities
. 2017-05-08 02:26:27.735 type=dir;modify=20170418084826;size=444;UNIX.mode=0755;UNIX.owner=root;UNIX.group=users; Temp
. 2017-05-08 02:26:27.735 type=dir;modify=20170421033140;size=272;UNIX.mode=0755;UNIX.owner=root;UNIX.group=users; Packages
. 2017-05-08 02:26:27.735 type=dir;modify=20161218090505;size=50;UNIX.mode=0755;UNIX.owner=root;UNIX.group=users; OpenBoxLab
. 2017-05-08 02:26:27.735 type=dir;modify=20170412133328;size=58;UNIX.mode=0755;UNIX.owner=root;UNIX.group=users; Media
. 2017-05-08 02:26:27.735 type=dir;modify=20170228065327;size=98;UNIX.mode=0755;UNIX.owner=root;UNIX.group=users; homes
. 2017-05-08 02:26:27.735 type=dir;modify=20170410134524;size=196;UNIX.mode=0755;UNIX.owner=root;UNIX.group=users; Family
. 2017-05-08 02:26:27.735 Got reply 1 to the command 2

....

> 2017-05-08 02:26:29.345 CWD /Temp/
< 2017-05-08 02:26:29.545 250 CWD command successful.
> 2017-05-08 02:26:29.545 PWD
< 2017-05-08 02:26:29.565 257 "/Temp" is current directory.
> 2017-05-08 02:26:29.565 TYPE A
< 2017-05-08 02:26:29.585 200 Type set to A.
> 2017-05-08 02:26:29.585 PASV
< 2017-05-08 02:26:29.595 227 Entering Passive Mode (192,168,200,40,216,247)
. 2017-05-08 02:26:29.595 Server sent passive reply with unroutable address 192.168.200.40, using host address instead.
> 2017-05-08 02:26:29.595 MLSD
< 2017-05-08 02:26:29.635 150 Opening BINARY mode SSL data connection for 'file list'.
. 2017-05-08 02:26:29.635 Session ID reused
. 2017-05-08 02:26:29.635 Using TLSv1.2, cipher TLSv1/SSLv3: AES256-GCM-SHA384, 2048 bit RSA, AES256-GCM-SHA384       TLSv1.2 Kx=RSA      Au=RSA  Enc=AESGCM(256) Mac=AEAD
< 2017-05-08 02:26:29.665 226 Transfer complete.
. 2017-05-08 02:26:29.675 Data connection closed
. 2017-05-08 02:26:29.675 type=file;modify=20170217161421;size=4025667167;UNIX.mode=0777;UNIX.owner=lanopk;UNIX.group=users; Big.Hero.6.2014.720p.BluRay.x264.DTS.2AUDiO-SODiHD.mkv
. 2017-05-08 02:26:29.675 type=dir;modify=20161118070028;size=0;UNIX.mode=0777;UNIX.owner=yogi0224;UNIX.group=users; RaiDrive.Packages
. 2017-05-08 02:26:29.675 type=file;modify=20170418084821;size=13968208;UNIX.mode=0777;UNIX.owner=lanopk;UNIX.group=users; RaiDrive_1.0.1.exe
. 2017-05-08 02:26:29.675 type=dir;modify=20170411073849;size=40;UNIX.mode=0777;UNIX.owner=lanopk;UNIX.group=users; ShellExtensionTest
. 2017-05-08 02:26:29.675 type=dir;modify=20170411061727;size=0;UNIX.mode=0777;UNIX.owner=yogi0224;UNIX.group=users; Torrent
. 2017-05-08 02:26:29.675 type=dir;modify=20170321003714;size=464;UNIX.mode=0777;UNIX.owner=lanopk;UNIX.group=users; dump
. 2017-05-08 02:26:29.675 type=dir;modify=20161123145229;size=27540;UNIX.mode=0777;UNIX.owner=yogi0224;UNIX.group=users; ~!@#$%^&()_+`-=[]{};',
. 2017-05-08 02:26:29.675 type=file;modify=20170307102136;size=0;UNIX.mode=0777;UNIX.owner=lanopk;UNIX.group=users; ~!@#$%^&()_+`-=[]{};',..txt
. 2017-05-08 02:26:29.675 type=file;modify=20170217143001;size=249012224;UNIX.mode=0777;UNIX.owner=lanopk;UNIX.group=users; 鍮④컯癒몃━ ??1[?붾튃].avi
. 2017-05-08 02:26:29.675 type=dir;modify=20170422064703;size=352;UNIX.mode=0777;UNIX.owner=lanopk;UNIX.group=users; ?ㅻ?寃?
. 2017-05-08 02:26:29.675 type=dir;modify=20170321050021;size=552;UNIX.mode=0777;UNIX.owner=lanopk;UNIX.group=users; ?ㅻ?寃?
. 2017-05-08 02:26:29.675 Got reply 1 to the command 2

**Comment by Zoltan666** [comment] 2017-05-07 23:45
The problem is in the FtpTrace.WriteLine method.

It gets called with the raw data from the FTP listing for each line. One of those lines contains curly braces. 
```
2017-05-08 02:26:29.675 type=dir;modify=20161123145229;size=27540;UNIX.mode=0777;UNIX.owner=yogi0224;UNIX.group=users; ~!@#$%^&()_+-=[]{};',
```
Because of the method signature the string version gets called which expects some args as the second parameter. The curly braces causes the String.Format call to try to use the args which are empty.

The simplest fix for this is to provide a 3rd WriteLine method in FtpTrace with a single string parameter. i.e.
```
public static void WriteLine(string message) {
	Write(string.Format("{0}{1}", message, Environment.NewLine));
}
```

**Comment by hgupta9** [comment] 2017-05-08 06:54
Thank you @Zoltan666 I'll apply that fix immediately.

**Comment by hgupta9** [comment] 2017-05-08 07:13
@lanopk Can you try beta 3 and see if it works for you?

- [FluentFTP_16.6_BETA3.zip](https://we.tl/RacNNpDN6C)

@Zoltan666 I've removed ALL usages of string.Format in the library due to its erratic behavior. No more such issues should ever come up. Thanks for the tip.

**Comment by hgupta9** [comment] 2017-05-08 10:13
Your right. My "fix" caused another bug that I now fixed. Can you try this?

- [FluentFTP_16.6_BETA4.zip](https://we.tl/hRjje8erPA)

**Comment by lanopk** [comment] 2017-05-08 11:09
OK. Beta4 works fine.
Thank you very much.

PS: I get some strange actions about OpenWrite and OpenAppend function.
The uploaded file is currupted.
I did upload file partially. First OpenWrite and OpenAppend, OpenAppend...
I will contact you if I know the exact details.

**Comment by hgupta9** [comment] 2017-05-08 12:22
Ok thats great. I'm closing this issue please open another one for another problem.

**Closed by hgupta9** 2017-05-08 12:22 UTC
Labels: bug, fixed, synology-nas

**Comment by Zoltan666** [comment] 2017-05-08 15:36
This bug was introduced here:
https://github.com/hgupta9/FluentFTP/commit/5ea06820f6f73517cde16d2abd066bd238109398#diff-5ad7528c69243efe00c853b3d6fb2965

I suspect there are now multiple new bugs due to the calls to String.Format being removed. I would strongly suggest backing out those changes and restore this version of FtpTrace.WriteLine that was correct.

String.Format is not erratic, its behaviour is very well defined. The above change broke FtpTrace.WriteLine.

**Comment by hgupta9** [comment] 2017-05-08 15:41
@Zoltan666 Thanks for that info. I have only removed the string.Format when its used for simple string concatenation. In a few other places where it was used for actual formatting I have left it. The only time I changed it is here:
https://github.com/hgupta9/FluentFTP/commit/3b6a5098342de525369faf0b05b4bdbd8c5ec347
