### ISSUE TITLE
Disposing a connected AsyncFtpClient throws non-fatal System.InvalidCastException in version 49.0.*

### ISSUE THREAD

**Issue by kmgallahan** [hgupta9/FluentFTP#1461] opened 2024-02-05 19:51 UTC
**FTP Server OS:** Windows

**FTP Server Type:** FileZilla Server

**Client Computer OS:** Windows

**FluentFTP Version:** 49.0.*

**Framework:** .NET 8

Updating to FluentFTP version 49.0.* and disposing of a connected `AsyncFtpClient` throws a non-fatal exception to debug output (unsure if this also applies to other client types):

```
Exception thrown: 'System.InvalidCastException' in System.Private.CoreLib.dll
```

Reverting to a lower version results in no such exception.

Exception is thrown from this line:

https://github.com/robinrodricks/FluentFTP/blob/bc0fb72021ef52eec3b3ce5485dec848f12ddb3d/FluentFTP/Client/BaseFtpClient.cs#L120

Looks like #1422 introduced it

**Logs :**

``` 
[14:45:08 INF] >         Connect(False) (FTP)
[14:45:08 DBG] FluentFTP 49.0.0.0(.NET 6.0) (FTP)
[14:45:08 INF] Connecting to IP #1= ***:21 (FTP)
[14:45:08 DBG] Waiting for a response (FTP)
[14:45:08 DBG] Response: 220-FileZilla Server 1.7.3 (FTP)
[14:45:08 INF] Response: 220 Please visit https://filezilla-project.org/ [738920.823d] (FTP)
[14:45:08 INF] Status:   Detected FTP server: FileZilla (FTP)
[14:45:08 INF] Command:  USER *** (FTP)
[14:45:08 DBG] Waiting for response to: USER *** (FTP)
[14:45:08 INF] Response: 331 Please, specify the password. [29ms] (FTP)
[14:45:08 INF] Command:  PASS *** (FTP)
[14:45:08 DBG] Waiting for response to: PASS *** (FTP)
[14:45:08 INF] Response: 230 Login successful. [68ms] (FTP)
[14:45:08 INF] Command:  FEAT (FTP)
[14:45:08 DBG] Waiting for response to: FEAT (FTP)
[14:45:08 DBG] Response: 211-Features:
Response: MDTM
Response: REST STREAM
Response: SIZE
Response: MLST type*;size*;modify*;perm*;
Response: MLSD
Response: AUTH SSL
Response: AUTH TLS
Response: PROT
Response: PBSZ
Response: UTF8
Response: TVFS
Response: EPSV
Response: EPRT
Response: MFMT (FTP)
[14:45:08 INF] Response: 211 End [57ms] (FTP)
[14:45:08 INF] Text encoding: System.Text.UTF8Encoding+UTF8EncodingSealed (FTP)
[14:45:08 INF] Command:  SYST (FTP)
[14:45:08 DBG] Waiting for response to: SYST (FTP)
[14:45:08 INF] Response: 215 UNIX emulated by FileZilla. [30ms] (FTP)
[14:45:08 DBG] Active ServerHandler is: FileZilla (FTP)
[14:45:08 DBG] Listing parser set to: Machine (FTP)
[14:45:09 INF] Command:  PWD (FTP)
[14:45:09 DBG] Waiting for response to: PWD (FTP)
[14:45:09 INF] Response: 257 "/" is current directory. [29ms] (FTP)
[14:45:09 INF] >         Dispose() (FTP)
[14:45:09 DBG] Disposing FtpClient object... (FTP)
Exception thrown: 'System.InvalidCastException' in System.Private.CoreLib.dll
[14:45:09 DBG] Closing/Disposing FtpSocketStream(control connection) (FTP)
```

**Comment by FanDjango** [comment] 2024-02-05 22:03
Thanks for reporting this. I will investigate.

**Comment by FanDjango** [comment] 2024-02-05 22:07
Possible duplicate: #1460

**Comment by FanDjango** [comment] 2024-02-05 22:37
I just tried this explicitly disposing an AsyncFtpClient in connected state (instead of calling Disconnect(..) ) and I get this:

```
Command:  TYPE I (<-Daemon)
Status:   Waiting for response to: TYPE I (<-Daemon)
Response: 200 Type set to I [3ms]

>         Dispose()
Status:   Disposing FtpClient object...
Status:   Closing/Disposing FtpSocketStream(control connection)
Status:   Daemon terminated
Finished
```

So I can't seem to reproduce it. What does your minimal code look like that produces your log?

**Comment by FanDjango** [comment] 2024-02-05 22:40
Ooops. I see the exception, so disregard the previous post. Investigating some more...

**Comment by kmgallahan** [comment] 2024-02-05 22:49
https://github.com/robinrodricks/FluentFTP/pull/1422/files#r1479021315

**Comment by kmgallahan** [comment] 2024-02-06 11:07
Sorry, I should have used different wording.

`AsyncFtpClient` doesn't have a dispose method, so it uses `BaseFtpClient`'s `Dispose`, which casts to `IInteralFtpClient` (as pointed out in first comment), which then gets its `DisconnectInternal` called, which resolves to use `BaseFtpClient`'s `Disconnect` (maybe because we are in the the `Dispose` of that class).

`BaseFtpClient` then casts to `IFtpClient` in all cases to call `Disconnect` (second PR comment), but we are an `AsyncFtpClient`, hence the InvalidCastException. A check of some sort needs to be made to see if a cast to `IAsyncFtpClient` or `IFtpClient` should be made for the `Disconnect` call.

**Comment by FanDjango** [comment] 2024-02-06 11:12
> Sorry, I should have used different wording.

No, no, it's ok. I'm on the same track by now.

There are a few places where this check `if (this is AsyncFtpClient) { ....` would be needed, in fact.

But for the special case of Dispose - it wouldn't need this complication, as it should not make a hidden call to "Execute("QUIT)" (which is in Disconnect),  if we are still connected. 

For this case, I propose removing that. He who calls Dispose before Disconnect should not expect FluentFTP to issue a "QUIT" command prior to closing the connection, right?


Instead, I think that for `client.Dispose()` to make a hidden call to `Execute("QUIT")` in case `IsConnected` is true, is a nono.

**Comment by FanDjango** [comment] 2024-02-06 11:19
> If IAsyncFtpClient maybe just .GetAwaiter().GetResult() or Task.Run to not block since we don't care about the connection anymore anyways.

Nice idea, sort of unclean though.

**Comment by FanDjango** [comment] 2024-02-06 11:25
Since we are slowly trying to get the kinks out of the ASYNC stuff, I wouldn't want "Dispose()" to block, firstly. And to potentially leave hanging tasks out there is sort of worrying, especially when one thinks of Dispose of "cleaning up nicely".

So I would rather remove the call to "DisconnectInternal" entirely, as a believe it is in the users responsibility to invoke Disconnect himself and not expect Dispose to do it for him. But then, others may be of a different opinion.

Otherwise I would really like a 
`await client.Dispose(token)`
analogous to the SYNC way of doing things, since in this case Dispose might block.

**Comment by kmgallahan** [comment] 2024-02-06 11:30
The proper way to handle it would be to implement `IAsyncDisposablew` `AsyncDispose` method:

https://learn.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-disposeasync

I'm not calling Dispose manually, rather just exiting `using` blocks in async methods which the above would then handle.

**Comment by FanDjango** [comment] 2024-02-06 13:52
I have merged a tenative "workaround" fix into the current master. It uses your suggestion of a "`.GetAwaiter().GetResult()`" and removes the exception.

I have made a note about "IAsyncDisposable".

**Comment by kmgallahan** [comment] 2024-02-06 14:10
Was worried about that but just covered my eyes and 🙏

What about in a new file `AsyncClient/DisposeAsync.cs`:

``` cs
using // ...

#if NETSTANDARD2_1_OR_GREATER || NET5_0_OR_GREATER
public partial class AsyncFtpClient : IAsyncDisposable
{
   // ... DisposeAsync implementation  
}
#endif
```

Note: I have no idea if this is a viable solution or not as I don't have adequate experience with how these preprocessor directives work with Nuget packaging.

I also don't know if you can add on more interfaces in another part of a partial class like this.

**Comment by kmgallahan** [comment] 2024-02-06 14:32
Although if the second note doesn't work then we could just modify the original class definition:

``` cs
#if ...
public partial class AsyncFtpClient : BaseFtpClient, IInternalFtpClient, IDisposable, IAsyncFtpClient, IAsyncDisposable
#else
public partial class AsyncFtpClient : BaseFtpClient, IInternalFtpClient, IDisposable, IAsyncFtpClient
#endif

**Comment by FanDjango** [comment] 2024-02-06 14:34
Yeah, that is more or less what will be needed.

It's a pity as we were trying to get less and less of these, or at least restrict them to very low level near the system kind of stuff.

The entire attempt to extract common code from async and sync code is always endangered by the often found need to invoke a high level api function from down under and then needing to "de-segregate".

Re your latest post: You don't have time for a quick check? I'm inundated right now with other things.

**Comment by kmgallahan** [comment] 2024-02-06 14:39
Check regarding note 1 or 2? 

As of yet I haven't even cloned the codebase, just used Resharper to decompiler the module while debugging the exception to step through the code and have been browsing on GitHub since.

**Comment by FanDjango** [comment] 2024-02-06 14:42
Never mind for the moment. Let's sleep on it.

**Comment by kmgallahan** [comment] 2024-02-06 15:36
I've tested things. Two solutions look like they will work (they build with errors anyways). One requires preprocessor directives, the other requires adding references to 2 packages.

Note that the best solution in both cases also involves modifying FtpSocketStream to implement DisposeAsync, since it is a `Stream` that has async disposables.

---
# Solution 1: Directives

``` cs
using System;
using System.Threading.Tasks;

namespace FluentFTP;

#if NETSTANDARD2_1_OR_GREATER || NET5_0_OR_GREATER
public partial class AsyncFtpClient : IAsyncDisposable
{
	public async ValueTask DisposeAsync() {
		// Perform async cleanup.
		await DisposeAsyncCore();

		// Suppress finalization.
		GC.SuppressFinalize(this);
	}

	protected virtual async ValueTask DisposeAsyncCore() {
		if (IsDisposed) {
			return;
		}

		// Fix: Hard catch and suppress all exceptions during disposing as there are constant issues with this method
		try {
			LogFunction(nameof(DisposeAsync));
			LogWithPrefix(FtpTraceLevel.Verbose, "Disposing " + this.ClientType + " object...");
		}
		catch {
		}

		try {
			if (IsConnected) {
				await Disconnect();
			}
		}
		catch {
		}

		if (m_stream != null) {
			try {
				await m_stream.DisposeAsync();
			}
			catch {
			}

			m_stream = null;
		}

		try {
			m_credentials = null;
			m_textEncoding = null;
			m_host = null;
		}
		catch {
		}

		IsDisposed = true;
	}
}
#endif
```

---
# Solution 2: PolySharp

[PolySharp](https://github.com/Sergio0694/PolySharp) generates the missing language features for us, but it does also require a ref to the other package below to enable `IAsyncDisposable` use. Otherwise same code as above less the directives.

`FluentFTP.csproj`:

``` XML
      <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="8.0.0" />
      <PackageReference Include="PolySharp" Version="1.14.1">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
```

**Comment by FanDjango** [comment] 2024-02-06 15:50
> Reverting to a lower version results in no such exception.

By the way, "Reverting to a lower version" by no means made the code execute asyncly - it probably reverted to sync further down the chain somewhere.

**Comment by kmgallahan** [comment] 2024-02-06 15:59
> the "easy" code will need to be brought active when the AsyncDisposable is not viable.

The existing Dispose with synchronous code should get called automatically when the async version is not available, or if and when AsyncFtpClient is used outside outside of an async context. Implementing both `IDisposable` & `IDisposableAsync` is encouraged.

> By the way, "Reverting to a lower version" by no means made the code execute asyncly - it probably reverted to sync further down the chain somewhere.

Right. I only showed up here because a bright red exception showed up in my debug output yesterday after revisiting an old project and upgrading packages. Figuring out it was an invisible call to Dispose in a lib was a treat...

**Comment by FanDjango** [comment] 2024-02-06 19:44
> Figuring out it was an invisible call to Dispose in a lib was a treat...

Well, although I am really sorry about that, when there was no bright red exception, you just were not aware that the code was runnic sync when disposing/disconnection. Probably the incurred short block on the QUIT command and GetReply was not to detrimental to be noticed.

**Comment by kmgallahan** [comment] 2024-02-06 20:05
Nothing to be sorry about, it's all just code. This was just a case of peeling back layers of an onion, which was interesting.

I'm glad we got a temporary fix in place and figured out a good path forward here.

**Comment by FanDjango** [comment] 2024-02-07 16:37
| also involves modifying FtpSocketStream to implement...

I see better now what you mean. `m_stream.DisposeAsync()`. Nifty, didn't know it existed.

**Comment by FanDjango** [comment] 2024-02-07 20:11
Gosh, thanks to your efforts I have put together a PR (tested and looks real nice) - would you like to try it and/or look at it (my branch for the PR is https://github.com/FanDjango/FluentFTP/tree/asynctest).

Users who don't want to add the **await** to their "using" statements, will get the .GetWaiter().GetResult() logic you proposed, also users who don't have one of the more modern .NETs.

**Comment by kmgallahan** [comment] 2024-02-08 03:00
Per my comment on the PR: https://github.com/robinrodricks/FluentFTP/pull/1466#discussion_r1482095992

We would need something like this:

``` cs
public override async ValueTask DisposeAsync() {
	// Perform async cleanup.
	await DisposeAsyncCore();

	// Maybe necessary
	await base.DisposeAsync();

	// Maybe necessary
	base.Dispose(false);

	// Suppress finalization.
	GC.SuppressFinalize(this);
}

protected async ValueTask DisposeAsyncCore() {
	if (m_customStream != null) {
		try {
			m_customStream.Dispose();
		}
		catch {
		}

		m_customStream = null;
	}


	if (m_sslStream != null) {
		try {
			await m_sslStream.DisposeAsync();
		}
		catch {
		}

		m_sslStream = null;
	}

	if (m_bufStream != null) {
		try {
			// ensure the last of the buffered bytes are flushed
			// before we close the socket and network stream
			await m_bufStream.FlushAsync();
		}
		catch {
		}

		m_bufStream = null;
	}

	if (m_netStream != null) {
		try {
			await m_netStream.DisposeAsync();
		}
		catch {
		}

		m_netStream = null;
	}

	DisposeSocket();

	if (Client.Status.DaemonRunning) {
		if (!this.IsControlConnection) {
			Client.Status.DaemonCmdMode = true;
		}
	}
}
```
Where:

- m_customStream: I don't know what this is used for
- m_sslStream: looks to be another stream implementation with some hacky stuff going on that would need to be cleaned up:

https://github.com/robinrodricks/FluentFTP/blob/341f7c8651e172e6344d353d6fb60451cb852746/FluentFTP/Streams/FtpSslStream.cs#L64

- m_bufStream: not custom, no extra work
- m_netStream: not custom, no extra work

**Comment by FanDjango** [comment] 2024-02-08 10:28
Let's merge this first part and consider the SocketStream disposal (cleanup) a separate issue for now.

> m_customStream: I don't know what this is used for

This is a drop-in placeholder for "other" stream implementations, currently needed and used for those who attach FluentFTP.GnuTls onto FluentFTP. This stream actually **does not** work async, those who use it thusly will have block issues.

> m_sslStream: looks to be another stream implementation with some hacky stuff going on that would need to be cleaned up

Hacky stuff, yes.

Disposal of an encrypted stream entails one or two TCP send operations to send commands to the other end (for orderly shutdown) and these could block. Without these commands, some servers will balk and report errors, thereby failing a transfer.

All other disposal concerns getting rid of buffers and other objects, tasks not likely to hurt you if they are not running async.

Therefore right now, it is my intention to defer the cleanup of SocketStream to a (say) "stage 2".

**Comment by FanDjango** [comment] 2024-02-08 10:53
> m_sslStream: looks to be another stream implementation with some hacky stuff

The thing about this one is that earlier sslStream implementations (by MicroSoft) did not issue the needed shutdown commands on the encrypted TCP connection prior to disposing. When they finally added that, they **only** put it into the DisposeAsync that they by then provided in the course of adding this language feature - with a subtle difference in which .NET versions it was included in and which ones not due to overlaps in the development teams schedules.

So getting this absolutely right needs a plethora of additional #IFDEFs etc.

For those versions that needed the hacky "manual" send of the commands, there is also a caveat.

You could have either of these following situations:

1. .NET is very old

You need the hacky manual command send and you cannot use DisposeAsync at all

So if in asyncClient you need .GetAwaiter and .GetResult

2. .NET is in a small range (spare me the effort to say exactly which)

You need the hacky manual commands **but** you could use DisposeAsync (which we don't do in the current code)

3. .NET is new

You don't need the hacky manual commands and you **can** use DisposeAsync

**Comment by FanDjango** [comment] 2024-02-08 10:57
> m_customStream

Here, things are quite clear. I could force implementation of DisposeAsync in the interface and an implementation of CustomStream (currently, only one) could internally go the .GetAwaiter.GetResult way (which the current one, GnuTlsStream, would need to do).

**Comment by kmgallahan** [comment] 2024-02-08 11:05
It probably is, but I'd make sure `m_stream.DisposeAsync` / `Stream.DisposeAsync` is calling `FtpSocketStream.Dispose`.

**Comment by FanDjango** [comment] 2024-02-16 09:29
FYI I have merged a number of PR's incrementally adding the CloseAsync/DisposeAsync patterns to FtpDataStream and FtpSocketStream into the current master, works as desired now.

Apart from a small caveat concerning closing/disposing SslStream/CustomStream, which may block (very short), all Async client APIs and methods are now diverted to AsyncClose/AsyncDispose instead of as previously, to sync.

I would appreciate it if you would take another look to see if you have additional items for this.

**Comment by kmgallahan** [comment] 2024-02-16 11:40
I think `m_bufStream` is (and has been) disposed synchronously. Perhaps add;

``` cs
			if (m_bufStream != null) {
				try {
					// ensure the last of the buffered bytes are flushed
					// before we close the socket and network stream
					await m_bufStream.FlushAsync();
#if NETSTANDARD2_1_OR_GREATER || NET5_0_OR_GREATER
					await m_bufStream.DisposeAsync();
#else
					((IInternalFtpClient)Client).LogStatus(FtpTraceLevel.Verbose, "Disposing(sync) FtpSslStream of FtpSocketStream");
					m_bufStream.Dispose(); // Async dispose not supported in this .NET?
#endif
				}
				catch {
				}
				m_bufStream = null;
			}
```

**Comment by kmgallahan** [comment] 2024-02-16 12:18
I just F12'd into it to check and this is how `BufferedStream` implements its DisposeAsync:

``` cs
        public override async ValueTask DisposeAsync()
        {
            try
            {
                if (_stream != null)
                {
                    try
                    {
                        await FlushAsync().ConfigureAwait(false);
                    }
                    finally
                    {
                        await _stream.DisposeAsync().ConfigureAwait(false);
                    }
                }
            }
            finally
            {
                _stream = null;
                _buffer = null;
                _writePos = 0;
            }
        }
```

So we can simplify the above to just call `DisposeAsync` instead of `FlushAsync`.

**Comment by FanDjango** [comment] 2024-02-16 12:42
I was coding from FtpSocketStream on upwards.

So, looking at BufferStream:

```
			if (m_bufStream != null) {
				try {
					m_bufStream.Flush();
				}
				catch {
				}
				m_bufStream = null;
			}
```
could actually be reduced to
```
m_bufStream.Dispose()
```
as the ==null, the try, etc, are all catered for anyway?

**Comment by kmgallahan** [comment] 2024-02-16 13:16
I did check version 4.7.2 of Dispose, and it also makes the flush call. I assume whenever DisposeAsync was introduced that it followed this logic.

**Comment by FanDjango** [comment] 2024-02-16 21:16
> In any case, by only ever calling Flush I don't think this BufferedStream was ever being cleaned up entirely.

Thankfully, it wasn't in universal use anyway for newer .NETs.

Why don't you submit a PR with the needed changes?

**Comment by FanDjango** [comment] 2024-02-17 10:18
Thanks for the PR, that saved some time. It's merged into the current master and anyone who has been having async glitches should put this through the grinder.

**Comment by FanDjango** [comment] 2024-02-29 10:10
Have you had a chance to use current master?

**Comment by kmgallahan** [comment] 2024-03-01 09:28
Seems to work fine, at least in a basic test app 👍

**Comment by FanDjango** [comment] 2024-03-04 16:32
Added some more small code changes to fix some glitches this caused in SYNC mode, of all places. Closing this now and thanks for the inpur

**Closed as completed** 2024-03-04 16:32 UTC
Labels: bug, fixed, maintenance
