### ISSUE TITLE
UploadFile stuck in while-loop

### ISSUE THREAD

**Issue by Fjomp08** [hgupta9/FluentFTP#46] opened 2017-02-06 10:48 UTC
When using UploadFile (stream, "path"); to a filename that already exists and the uploaded file is smaller than the existing one. Then UploadFileInternal gets stuck in the empty while-loop, since upStream.Length is bigger than upStream.Position.

**Comment by hgupta9** [comment] 2017-02-06 11:01
Thanks for reporting this. We'll work on a fix as soon as possible. For now best way is to DeleteFile() and the UploadFile()

**Comment by daveaglick** [comment] 2017-02-17 15:16
I can confirm the same problem. Deleting before uploading seems to resolve the issue for me.

**Comment by stefanouic** [comment] 2017-02-22 10:35
I can confirm the same problem. 
I've tried the following versions: 16.2.0 and 16.2.1.
Now, instead of upload with overwrite I'm doing a delete upload (with no overwrite).

**Comment by hgupta9** [comment] 2017-02-22 17:07
@Fjomp08 @stefanouic 
I've implemented a fix for this in 16.2.3. Can you guys check and see if it works? I'm internally checking for the file existence before every upload, and deleting the file if it exists before uploading. I had earlier assumed that using OpenWrite would guarantee that the remote file is overwritten, but since all of you have problems with that I had to implement such a fix.

@daveaglick - Can you try uploading without DeleteFile() and see if all goes ok?

**Comment by daveaglick** [comment] 2017-03-06 21:51
I'm still having trouble with this in 16.2.4. When I attempt to `UploadFile()` without first doing a `FileExists()` followed by a `DeleteFile()`, I get timeouts similar to #55.

**Comment by hgupta9** [comment] 2017-03-08 05:53
@daveaglick - Thats very strange. Because I'm simply doing a `FileExists()` check internally then `DeleteFile()` if the file exists. No other code has been added/changed.

**Comment by przemekwa** [comment] 2017-04-05 09:14
I having this trouble with 16.3.0.0 ( filename that already exists and the uploaded file is smaller than the existing one. )

Can You fix this, I need Your dll on production site?

**Comment by hgupta9** [comment] 2017-04-06 09:39
@przemekwa - Can you ensure that `checkFileExistance ` is true? If its true there should be no problem...

**Comment by przemekwa** [comment] 2017-04-06 10:16
OK, I have `false `

`client.UploadFile(fs, txtFilePath, true, true, false);`

OK, I will check and I  will back to you with feedback.

Thx.

**Comment by hgupta9** [comment] 2017-05-09 07:06
I'm closing this. If you are still having this issue then add a comment and I'll reopen it.

**Closed by hgupta9** 2017-05-09 07:06 UTC
Labels: fixed, possible bug
