### ISSUE TITLE
OpenWrite - too many connections

### ISSUE THREAD

**Issue by altmann** [hgupta9/FluentFTP#34] opened 2017-01-21 21:35 UTC
Hi, 

if I upload multiple streams I get the error that the server can't accept more then 8 connections from the same username. I have some logic (see code) which checks if the stream is uploaded completly but I think the ftpClient doesn't close the connection. How I can close the connection/stream for OpenWrite?

_ftpClient.Connect();

            long origLength = stream.Length;

            using (var ftpStream = _ftpClient.OpenWrite(filePath, isBinary ? FtpDataType.Binary : FtpDataType.ASCII))
            {
                try
                {
                    stream.CopyTo(ftpStream);
                    Thread.Sleep(1000);

                    //byte[] buf = new byte[8192];
                    //int read = 0;

                    //while ((read = stream.Read(buf, 0, buf.Length)) > 0)
                    //{
                    //    ftpStream.Write(buf, 0, read);
                    //}
                }
                finally
                {
                    ftpStream.Close();
                    stream.Close();
                }

                long fileSizeOnFtp = _ftpClient.GetFileSize(filePath);
                while (fileSizeOnFtp < origLength)
                {
                    if (fileSizeOnFtp > -1)
                    {
                        fileSizeOnFtp = _ftpClient.GetFileSize(filePath);
                        Thread.Sleep(2000);
                    }
                    else
                    {
                        Thread.Sleep(3000);
                    }
                }

**Comment by hgupta9** [comment] 2017-01-22 07:27
Since you are simply uploading a file can you try the new `UploadFile()` API? it supports uploading of files and streams.

Also, OpenWrite is async. Meaning you have to specify a callback and close it there.

**Comment by altmann** [comment] 2017-01-22 08:08
With UploadFile() I get the same exception. "I can't accept more than 8 connections as the same user". You write OpenWrite is async. How I can pass a callback to close the stream? Some other ideas?

        public void CreateFile(string filePath, MemoryStream stream, bool isBinary)
        {
            _ftpClient.Connect();

            _ftpClient.UploadFile(stream, filePath);

            long origLength = stream.Length;
            long fileSizeOnFtp = _ftpClient.GetFileSize(filePath);
            while (fileSizeOnFtp < origLength)
            {
                if (fileSizeOnFtp > -1)
                {
                    Thread.Sleep(2000);
                    fileSizeOnFtp = _ftpClient.GetFileSize(filePath);
                }
                else
                {
                    Thread.Sleep(2000);
                }
            }
            _ftpClient.Disconnect();
        }

**Comment by hgupta9** [comment] 2017-01-22 09:58
I think the problem is you are connecting and disconnecting every file transfer. This may cause the server to think the connection is still open. Can you try this. 

    // initialize it once only
    _ftpClient.Connect();

    public void CreateFile(string filePath, MemoryStream stream, bool isBinary)
    {
        _ftpClient.UploadFile(stream, filePath);
    }

    // disconnect when all jobs are done
    _ftpClient.Disconnect();

How are you calling this function? Is it on multiple threads or just one thread?

**Comment by altmann** [comment] 2017-01-23 11:33
I also tried it with only once calling Connect/Disconnect and do all file transfers within one connection, but the same exception occur. It seems that the closing/disposing mechanism of file transfers doesn't work correctly. The first 8 files are transfered successfully but then I have no "free" connection and I get the exception.

**Comment by hgupta9** [comment] 2017-01-23 17:13
I'm sorry but I don't understand enough of the library to debug this issue. I know that for file transfers a new FTP thread is opened in active mode. Can you try passive mode and see if that is reliable for you?

    DataConnectionType = FtpDataConnectionType.Passive

Also just try adding a delay after uploads to see if that works.

    Thread.Sleep(5000); // try 5, 10 or 30 secs

**Comment by hgupta9** [comment] 2017-01-30 15:05
I've fixed this issue in the latest version which you can grab from nuget. I've set `EnableThreadSafeDataConnections = false` by default, and I've fixed the `UploadFile()` and `DownloadFile()` methods to be compatible with that setting. Keep that setting FALSE or don't bother changing it in your code. Can you see if this version works for you?

**Comment by altmann** [comment] 2017-02-05 14:00
Same behaviour (same exception) like in the previous version. If I set EnableThreadSafeDataConnections to false it works. If I set EnableThreadSafeDataConnections to true it doesn't work.

**Comment by hgupta9** [comment] 2017-02-05 15:35
Please set it to false. Its the new default in the library. Or just delete the line modifying it. UploadFile and DownloadFile work fine with it false.

**Closed by hgupta9** 2017-02-05 15:35 UTC
Labels: work-in-progress
